import { ValidZones } from "../static/AllowedZones";
type ZoneObj = {Name: ValidZones, Rate: Number}
export const ZONE_EORZEA: ZoneObj = {Name: "Eorzea", Rate: 0}
export const ZONE_NEW_GRIDANIA: ZoneObj = {Name: "New Gridania", Rate: 1}
export const ZONE_OLD_GRIDANIA: ZoneObj = {Name: "Old Gridania", Rate: 2}
export const ZONE_CENTRAL_SHROUD: ZoneObj = {Name: "Central Shroud", Rate: 3}
export const ZONE_EAST_SHROUD: ZoneObj = {Name: "East Shroud", Rate: 4}
export const ZONE_SOUTH_SHROUD: ZoneObj = {Name: "South Shroud", Rate: 5}
export const ZONE_NORTH_SHROUD: ZoneObj = {Name: "North Shroud", Rate: 6}
export const ZONE_THE_TAMTARA_DEEPCROFT: ZoneObj = {Name: "The Tam-Tara Deepcroft", Rate: 0}
export const ZONE_THE_THOUSAND_MAWS_OF_TOTORAK: ZoneObj = {Name: "The Thousand Maws of Toto-Rak", Rate: 0}
export const ZONE_MORDION_GAOL: ZoneObj = {Name: "Mordion Gaol", Rate: 0}
export const ZONE_LIMSA_LOMINSA_UPPER_DECKS: ZoneObj = {Name: "Limsa Lominsa Upper Decks", Rate: 14}
export const ZONE_LIMSA_LOMINSA_LOWER_DECKS: ZoneObj = {Name: "Limsa Lominsa Lower Decks", Rate: 15}
export const ZONE_ULDAH__STEPS_OF_NALD: ZoneObj = {Name: "Ul'dah - Steps of Nald", Rate: 7}
export const ZONE_ULDAH__STEPS_OF_THAL: ZoneObj = {Name: "Ul'dah - Steps of Thal", Rate: 8}
export const ZONE_MIDDLE_LA_NOSCEA: ZoneObj = {Name: "Middle La Noscea", Rate: 16}
export const ZONE_LOWER_LA_NOSCEA: ZoneObj = {Name: "Lower La Noscea", Rate: 17}
export const ZONE_EASTERN_LA_NOSCEA: ZoneObj = {Name: "Eastern La Noscea", Rate: 18}
export const ZONE_WESTERN_LA_NOSCEA: ZoneObj = {Name: "Western La Noscea", Rate: 19}
export const ZONE_UPPER_LA_NOSCEA: ZoneObj = {Name: "Upper La Noscea", Rate: 20}
export const ZONE_WESTERN_THANALAN: ZoneObj = {Name: "Western Thanalan", Rate: 9}
export const ZONE_CENTRAL_THANALAN: ZoneObj = {Name: "Central Thanalan", Rate: 10}
export const ZONE_EASTERN_THANALAN: ZoneObj = {Name: "Eastern Thanalan", Rate: 11}
export const ZONE_SOUTHERN_THANALAN: ZoneObj = {Name: "Southern Thanalan", Rate: 12}
export const ZONE_NORTHERN_THANALAN: ZoneObj = {Name: "Northern Thanalan", Rate: 13}
export const ZONE_MOR_DHONA: ZoneObj = {Name: "Mor Dhona", Rate: 22}
export const ZONE_MIZZENMAST_INN: ZoneObj = {Name: "Mizzenmast Inn", Rate: 0}
export const ZONE_THE_HOURGLASS: ZoneObj = {Name: "The Hourglass", Rate: 0}
export const ZONE_THE_ROOST: ZoneObj = {Name: "The Roost", Rate: 0}
export const ZONE_OUTER_LA_NOSCEA: ZoneObj = {Name: "Outer La Noscea", Rate: 24}
export const ZONE_SASTASHA: ZoneObj = {Name: "Sastasha", Rate: 0}
export const ZONE_THE_WANDERERS_PALACE: ZoneObj = {Name: "The Wanderer's Palace", Rate: 0}
export const ZONE_THE_NAVEL: ZoneObj = {Name: "The Navel", Rate: 23}
export const ZONE_COPPERBELL_MINES: ZoneObj = {Name: "Copperbell Mines", Rate: 0}
export const ZONE_BOWL_OF_EMBERS: ZoneObj = {Name: "Bowl of Embers", Rate: 25}
export const ZONE_THORNMARCH: ZoneObj = {Name: "Thornmarch", Rate: 30}
export const ZONE_STONE_VIGIL: ZoneObj = {Name: "Stone Vigil", Rate: 27}
export const ZONE_AURUM_VALE: ZoneObj = {Name: "Aurum Vale", Rate: 0}
export const ZONE_THE_HOWLING_EYE: ZoneObj = {Name: "The Howling Eye", Rate: 26}
export const ZONE_THE_SUNKEN_TEMPLE_OF_QARN: ZoneObj = {Name: "The Sunken Temple of Qarn", Rate: 0}
export const ZONE_BRAYFLOXS_LONGSTOP: ZoneObj = {Name: "Brayflox's Longstop", Rate: 0}
export const ZONE_HALATALI: ZoneObj = {Name: "Halatali", Rate: 0}
export const ZONE_CASTRUM_MERIDIANUM: ZoneObj = {Name: "Castrum Meridianum", Rate: 0}
export const ZONE_HAUKKE_MANOR: ZoneObj = {Name: "Haukke Manor", Rate: 0}
export const ZONE_AMDAPOR_KEEP: ZoneObj = {Name: "Amdapor Keep", Rate: 28}
export const ZONE_DZEMAEL_DARKHOLD: ZoneObj = {Name: "Dzemael Darkhold", Rate: 0}
export const ZONE_WOLVES_DEN_PIER: ZoneObj = {Name: "Wolves' Den Pier", Rate: 29}
export const ZONE_CUTTERS_CRY: ZoneObj = {Name: "Cutter's Cry", Rate: 0}
export const ZONE_COERTHAS_CENTRAL_HIGHLANDS: ZoneObj = {Name: "Coerthas Central Highlands", Rate: 21}
export const ZONE_THE_PRAETORIUM: ZoneObj = {Name: "The Praetorium", Rate: 0}
export const ZONE_UPPER_AETHEROACOUSTIC_EXPLORATORY_SITE: ZoneObj = {Name: "Upper Aetheroacoustic Exploratory Site", Rate: 0}
export const ZONE_LOWER_AETHEROACOUSTIC_EXPLORATORY_SITE: ZoneObj = {Name: "Lower Aetheroacoustic Exploratory Site", Rate: 0}
export const ZONE_RAGNAROK_DRIVE_CYLINDER: ZoneObj = {Name: "Ragnarok Drive Cylinder", Rate: 0}
export const ZONE_RAGNAROK_CENTRAL_CORE: ZoneObj = {Name: "Ragnarok Central Core", Rate: 0}
export const ZONE_RAGNAROK_MAIN_BRIDGE: ZoneObj = {Name: "Ragnarok Main Bridge", Rate: 0}
export const ZONE_THE_RAGNAROK: ZoneObj = {Name: "The Ragnarok", Rate: 0}
export const ZONE_CENTRAL_DECKS: ZoneObj = {Name: "Central Decks", Rate: 0}
export const ZONE_SEAT_OF_THE_FIRST_BOW: ZoneObj = {Name: "Seat of the First Bow", Rate: 0}
export const ZONE_LOTUS_STAND: ZoneObj = {Name: "Lotus Stand", Rate: 0}
export const ZONE_LABYRINTH_OF_THE_ANCIENTS: ZoneObj = {Name: "Labyrinth of the Ancients", Rate: 0}
export const ZONE_MIST: ZoneObj = {Name: "Mist", Rate: 32}
export const ZONE_COMMAND_ROOM: ZoneObj = {Name: "Command Room", Rate: 14}
export const ZONE_THE_MEMORY_OF_EMBERS: ZoneObj = {Name: "The Memory of Embers", Rate: 155}
export const ZONE_HEART_OF_THE_SWORN: ZoneObj = {Name: "Heart of the Sworn", Rate: 0}
export const ZONE_THE_WAKING_SANDS: ZoneObj = {Name: "The Waking Sands", Rate: 0}
export const ZONE_THE_FOLD: ZoneObj = {Name: "The Fold", Rate: 0}
export const ZONE_THE_LAVENDER_BEDS: ZoneObj = {Name: "The Lavender Beds", Rate: 34}
export const ZONE_THE_GOBLET: ZoneObj = {Name: "The Goblet", Rate: 33}
export const ZONE_EORZEAN_SUBTERRANE: ZoneObj = {Name: "Eorzean Subterrane", Rate: 0}
export const ZONE_PHAROS_SIRIUS: ZoneObj = {Name: "Pharos Sirius", Rate: 28}
export const ZONE_PRIVATE_COTTAGE__MIST: ZoneObj = {Name: "Private Cottage - Mist", Rate: 0}
export const ZONE_PRIVATE_HOUSE__MIST: ZoneObj = {Name: "Private House - Mist", Rate: 0}
export const ZONE_PRIVATE_MANSION__MIST: ZoneObj = {Name: "Private Mansion - Mist", Rate: 0}
export const ZONE_PRIVATE_COTTAGE__THE_LAVENDER_BEDS: ZoneObj = {Name: "Private Cottage - The Lavender Beds", Rate: 0}
export const ZONE_PRIVATE_HOUSE__THE_LAVENDER_BEDS: ZoneObj = {Name: "Private House - The Lavender Beds", Rate: 0}
export const ZONE_PRIVATE_MANSION__THE_LAVENDER_BEDS: ZoneObj = {Name: "Private Mansion - The Lavender Beds", Rate: 0}
export const ZONE_PRIVATE_COTTAGE__THE_GOBLET: ZoneObj = {Name: "Private Cottage - The Goblet", Rate: 0}
export const ZONE_PRIVATE_HOUSE__THE_GOBLET: ZoneObj = {Name: "Private House - The Goblet", Rate: 0}
export const ZONE_PRIVATE_MANSION__THE_GOBLET: ZoneObj = {Name: "Private Mansion - The Goblet", Rate: 0}
export const ZONE_THE_RISING_STONES: ZoneObj = {Name: "The Rising Stones", Rate: 0}
export const ZONE_HAUKKE_MANOR_HARD: ZoneObj = {Name: "Haukke Manor (Hard)", Rate: 0}
export const ZONE_COPPERBELL_MINES_HARD: ZoneObj = {Name: "Copperbell Mines (Hard)", Rate: 0}
export const ZONE_PORTA_DECUMANA: ZoneObj = {Name: "Porta Decumana", Rate: 31}
export const ZONE_GRIFFIN_CROSSING: ZoneObj = {Name: "Griffin Crossing", Rate: 0}
export const ZONE_HALATALI_HARD: ZoneObj = {Name: "Halatali (Hard)", Rate: 0}
export const ZONE_BRAYFLOXS_LONGSTOP_HARD: ZoneObj = {Name: "Brayflox's Longstop (Hard)", Rate: 37}
export const ZONE_THE_WHORLEATER: ZoneObj = {Name: "The Whorleater", Rate: 38}
export const ZONE_DALAMUDS_SHADOW: ZoneObj = {Name: "Dalamud's Shadow", Rate: 0}
export const ZONE_THE_OUTER_COIL: ZoneObj = {Name: "The Outer Coil", Rate: 28}
export const ZONE_THE_HOLOCHARTS: ZoneObj = {Name: "The Holocharts", Rate: 0}
export const ZONE_THE_LOST_CITY_OF_AMDAPOR: ZoneObj = {Name: "The Lost City of Amdapor", Rate: 40}
export const ZONE_THE_STONE_VIGIL_HARD: ZoneObj = {Name: "The Stone Vigil (Hard)", Rate: 42}
export const ZONE_SYRCUS_TOWER: ZoneObj = {Name: "Syrcus Tower", Rate: 0}
export const ZONE_THE_TAMTARA_DEEPCROFT_HARD: ZoneObj = {Name: "The Tam-Tara Deepcroft (Hard)", Rate: 0}
export const ZONE_THE_STRIKING_TREE: ZoneObj = {Name: "The Striking Tree", Rate: 43}
export const ZONE_CARTENEAU_FLATS_BORDERLAND_RUINS: ZoneObj = {Name: "Carteneau Flats: Borderland Ruins", Rate: 0}
export const ZONE_HULLBREAKER_ISLE: ZoneObj = {Name: "Hullbreaker Isle", Rate: 0}
export const ZONE_SASTASHA_HARD: ZoneObj = {Name: "Sastasha (Hard)", Rate: 0}
export const ZONE_PRIVATE_CHAMBERS__MIST: ZoneObj = {Name: "Private Chambers - Mist", Rate: 0}
export const ZONE_PRIVATE_CHAMBERS__THE_LAVENDER_BEDS: ZoneObj = {Name: "Private Chambers - The Lavender Beds", Rate: 0}
export const ZONE_PRIVATE_CHAMBERS__THE_GOBLET: ZoneObj = {Name: "Private Chambers - The Goblet", Rate: 0}
export const ZONE_AKH_AFAH_AMPHITHEATRE: ZoneObj = {Name: "Akh Afah Amphitheatre", Rate: 46}
export const ZONE_SNOWCLOAK: ZoneObj = {Name: "Snowcloak", Rate: 42}
export const ZONE_IC06_CENTRAL_DECKS: ZoneObj = {Name: "IC-06 Central Decks", Rate: 0}
export const ZONE_IC06_REGENERATION_GRID: ZoneObj = {Name: "IC-06 Regeneration Grid", Rate: 0}
export const ZONE_IC06_MAIN_BRIDGE: ZoneObj = {Name: "IC-06 Main Bridge", Rate: 0}
export const ZONE_THE_BURNING_HEART: ZoneObj = {Name: "The Burning Heart", Rate: 44}
export const ZONE_INTERCESSORY: ZoneObj = {Name: "Intercessory", Rate: 0}
export const ZONE_THE_SUNKEN_TEMPLE_OF_QARN_HARD: ZoneObj = {Name: "The Sunken Temple of Qarn (Hard)", Rate: 41}
export const ZONE_THE_WORLD_OF_DARKNESS: ZoneObj = {Name: "The World of Darkness", Rate: 0}
export const ZONE_THE_BELLY_OF_THE_BEAST: ZoneObj = {Name: "The Belly of the Beast", Rate: 0}
export const ZONE_STEPS_OF_FAITH: ZoneObj = {Name: "Steps of Faith", Rate: 28}
export const ZONE_THE_WANDERERS_PALACE_HARD: ZoneObj = {Name: "The Wanderer's Palace (Hard)", Rate: 40}
export const ZONE_AMDAPOR_KEEP_HARD: ZoneObj = {Name: "Amdapor Keep (Hard)", Rate: 40}
export const ZONE_THE_GOLD_SAUCER: ZoneObj = {Name: "The Gold Saucer", Rate: 0}
export const ZONE_CHOCOBO_SQUARE: ZoneObj = {Name: "Chocobo Square", Rate: 0}
export const ZONE_THE_KEEPER_OF_THE_LAKE: ZoneObj = {Name: "The Keeper of the Lake", Rate: 74}
export const ZONE_COMPANY_WORKSHOP__MIST: ZoneObj = {Name: "Company Workshop - Mist", Rate: 0}
export const ZONE_COMPANY_WORKSHOP__THE_GOBLET: ZoneObj = {Name: "Company Workshop - The Goblet", Rate: 0}
export const ZONE_COMPANY_WORKSHOP__THE_LAVENDER_BEDS: ZoneObj = {Name: "Company Workshop - The Lavender Beds", Rate: 0}
export const ZONE_THE_CHRYSALIS: ZoneObj = {Name: "The Chrysalis", Rate: 0}
export const ZONE_SANCTUM_OF_THE_TWELVE: ZoneObj = {Name: "Sanctum of the Twelve", Rate: 4}
export const ZONE_COERTHAS_WESTERN_HIGHLANDS: ZoneObj = {Name: "Coerthas Western Highlands", Rate: 49}
export const ZONE_THE_DRAVANIAN_FORELANDS: ZoneObj = {Name: "The Dravanian Forelands", Rate: 50}
export const ZONE_THE_DRAVANIAN_HINTERLANDS: ZoneObj = {Name: "The Dravanian Hinterlands", Rate: 51}
export const ZONE_THE_CHURNING_MISTS: ZoneObj = {Name: "The Churning Mists", Rate: 52}
export const ZONE_THE_SEA_OF_CLOUDS: ZoneObj = {Name: "The Sea of Clouds", Rate: 53}
export const ZONE_AZYS_LLA: ZoneObj = {Name: "Azys Lla", Rate: 54}
export const ZONE_FOUNDATION: ZoneObj = {Name: "Foundation", Rate: 47}
export const ZONE_THE_PILLARS: ZoneObj = {Name: "The Pillars", Rate: 48}
export const ZONE_SAINT_ENDALIMS_SCHOLASTICATE: ZoneObj = {Name: "Saint Endalim's Scholasticate", Rate: 0}
export const ZONE_SEAT_OF_THE_LORD_COMMANDER: ZoneObj = {Name: "Seat of the Lord Commander", Rate: 0}
export const ZONE_FORTEMPS_MANOR: ZoneObj = {Name: "Fortemps Manor", Rate: 0}
export const ZONE_CLOUD_NINE: ZoneObj = {Name: "Cloud Nine", Rate: 0}
export const ZONE_THE_LIGHTFEATHER_PROVING_GROUNDS: ZoneObj = {Name: "The Lightfeather Proving Grounds", Rate: 0}
export const ZONE_RULING_CHAMBER: ZoneObj = {Name: "Ruling Chamber", Rate: 0}
export const ZONE_SACRIFICIAL_CHAMBER: ZoneObj = {Name: "Sacrificial Chamber", Rate: 0}
export const ZONE_SOHM_AL_FOOTHILLS: ZoneObj = {Name: "Sohm Al Foothills", Rate: 0}
export const ZONE_NEVERREAP: ZoneObj = {Name: "Neverreap", Rate: 0}
export const ZONE_AETHEROCHEMICAL_RESEARCH_FACILITY: ZoneObj = {Name: "Aetherochemical Research Facility", Rate: 0}
export const ZONE_THE_LIMITLESS_BLUE: ZoneObj = {Name: "The Limitless Blue", Rate: 28}
export const ZONE_SINGULARITY_REACTOR: ZoneObj = {Name: "Singularity Reactor", Rate: 56}
export const ZONE_THE_FIST_OF_THE_FATHER: ZoneObj = {Name: "The Fist of the Father", Rate: 0}
export const ZONE_THE_CUFF_OF_THE_FATHER: ZoneObj = {Name: "The Cuff of the Father", Rate: 0}
export const ZONE_THE_ARM_OF_THE_FATHER: ZoneObj = {Name: "The Arm of the Father", Rate: 0}
export const ZONE_THE_BURDEN_OF_THE_FATHER: ZoneObj = {Name: "The Burden of the Father", Rate: 0}
export const ZONE_THE_GREAT_GUBAL_LIBRARY: ZoneObj = {Name: "The Great Gubal Library", Rate: 0}
export const ZONE_SEAL_ROCK: ZoneObj = {Name: "Seal Rock", Rate: 59}
export const ZONE_DUSK_VIGIL: ZoneObj = {Name: "Dusk Vigil", Rate: 42}
export const ZONE_THE_FRACTAL_CONTINUUM: ZoneObj = {Name: "The Fractal Continuum", Rate: 0}
export const ZONE_THE_VAULT: ZoneObj = {Name: "The Vault", Rate: 0}
export const ZONE_THE_AERY: ZoneObj = {Name: "The Aery", Rate: 28}
export const ZONE_MATOYAS_CAVE: ZoneObj = {Name: "Matoya's Cave", Rate: 0}
export const ZONE_THOK_AST_THOK: ZoneObj = {Name: "Thok ast Thok", Rate: 57}
export const ZONE_IDYLLSHIRE: ZoneObj = {Name: "Idyllshire", Rate: 55}
export const ZONE_THE_GORDIAN_KNOT: ZoneObj = {Name: "The Gordian Knot", Rate: 0}
export const ZONE_CENTRAL_AZYS_LLA: ZoneObj = {Name: "Central Azys Lla", Rate: 0}
export const ZONE_PHAROS_SIRIUS_HARD: ZoneObj = {Name: "Pharos Sirius (Hard)", Rate: 28}
export const ZONE_THE_EIGHTEENTH_FLOOR: ZoneObj = {Name: "The Eighteenth Floor", Rate: 0}
export const ZONE_SAINT_MOCIANNES_ARBORETUM: ZoneObj = {Name: "Saint Mocianne's Arboretum", Rate: 0}
export const ZONE_VOID_ARK: ZoneObj = {Name: "Void Ark", Rate: 37}
export const ZONE_THE_ANTITOWER: ZoneObj = {Name: "The Antitower", Rate: 0}
export const ZONE_THE_LOST_CITY_OF_AMDAPOR_HARD: ZoneObj = {Name: "The Lost City of Amdapor (Hard)", Rate: 63}
export const ZONE_CONTAINMENT_BAY_S1T7: ZoneObj = {Name: "Containment Bay S1T7", Rate: 66}
export const ZONE_THE_FEASTING_GROUNDS: ZoneObj = {Name: "The Feasting Grounds", Rate: 0}
export const ZONE_THE_FIST_OF_THE_SON: ZoneObj = {Name: "The Fist of the Son", Rate: 0}
export const ZONE_THE_CUFF_OF_THE_SON: ZoneObj = {Name: "The Cuff of the Son", Rate: 0}
export const ZONE_THE_ARM_OF_THE_SON: ZoneObj = {Name: "The Arm of the Son", Rate: 0}
export const ZONE_THE_BURDEN_OF_THE_SON: ZoneObj = {Name: "The Burden of the Son", Rate: 0}
export const ZONE_THE_MIDAN_KNOT: ZoneObj = {Name: "The Midan Knot", Rate: 0}
export const ZONE_SOHR_KHAI: ZoneObj = {Name: "Sohr Khai", Rate: 0}
export const ZONE_THE_BATTLEHALL: ZoneObj = {Name: "The Battlehall", Rate: 0}
export const ZONE_THE_FIELDS_OF_GLORY: ZoneObj = {Name: "The Fields of Glory", Rate: 67}
export const ZONE_HULLBREAKER_ISLE_HARD: ZoneObj = {Name: "Hullbreaker Isle (Hard)", Rate: 68}
export const ZONE_THE_WEEPING_CITY_OF_MHACH: ZoneObj = {Name: "The Weeping City of Mhach", Rate: 0}
export const ZONE_THE_PARROCK: ZoneObj = {Name: "The Parrock", Rate: 0}
export const ZONE_LEOFARDS_CHAMBERS: ZoneObj = {Name: "Leofard's Chambers", Rate: 0}
export const ZONE_TWIN_ADDER_BARRACKS: ZoneObj = {Name: "Twin Adder Barracks", Rate: 0}
export const ZONE_FLAME_BARRACKS: ZoneObj = {Name: "Flame Barracks", Rate: 0}
export const ZONE_MAELSTROM_BARRACKS: ZoneObj = {Name: "Maelstrom Barracks", Rate: 0}
export const ZONE_THE_GREAT_GUBAL_LIBRARY_HARD: ZoneObj = {Name: "The Great Gubal Library (Hard)", Rate: 0}
export const ZONE_XELPHATOL: ZoneObj = {Name: "Xelphatol", Rate: 40}
export const ZONE_THE_PALACE_OF_THE_DEAD: ZoneObj = {Name: "The Palace of the Dead", Rate: 0}
export const ZONE_THE_AQUAPOLIS: ZoneObj = {Name: "The Aquapolis", Rate: 0}
export const ZONE_LAST_REMNANT: ZoneObj = {Name: "Last Remnant", Rate: 0}
export const ZONE_HAUNTED_MANOR: ZoneObj = {Name: "Haunted Manor", Rate: 0}
export const ZONE_TOPMAST_APARTMENT_LOBBY: ZoneObj = {Name: "Topmast Apartment Lobby", Rate: 0}
export const ZONE_LILY_HILLS_APARTMENT_LOBBY: ZoneObj = {Name: "Lily Hills Apartment Lobby", Rate: 0}
export const ZONE_SULTANAS_BREATH_APARTMENT_LOBBY: ZoneObj = {Name: "Sultana's Breath Apartment Lobby", Rate: 0}
export const ZONE_TOPMAST_APARTMENT: ZoneObj = {Name: "Topmast Apartment", Rate: 0}
export const ZONE_LILY_HILLS_APARTMENT: ZoneObj = {Name: "Lily Hills Apartment", Rate: 0}
export const ZONE_SULTANAS_BREATH_APARTMENT: ZoneObj = {Name: "Sultana's Breath Apartment", Rate: 0}
export const ZONE_EYES_OF_THE_CREATOR: ZoneObj = {Name: "Eyes of the Creator", Rate: 0}
export const ZONE_BREATH_OF_THE_CREATOR: ZoneObj = {Name: "Breath of the Creator", Rate: 0}
export const ZONE_HEART_OF_THE_CREATOR: ZoneObj = {Name: "Heart of the Creator", Rate: 0}
export const ZONE_SOUL_OF_THE_CREATOR: ZoneObj = {Name: "Soul of the Creator", Rate: 0}
export const ZONE_CONTAINMENT_BAY_P1T6: ZoneObj = {Name: "Containment Bay P1T6", Rate: 69}
export const ZONE_FRONDALES_HOME_FOR_FRIENDLESS_FOUNDLINGS: ZoneObj = {Name: "Frondale's Home for Friendless Foundlings", Rate: 0}
export const ZONE_SHISUI_OF_THE_VIOLET_TIDES: ZoneObj = {Name: "Shisui of the Violet Tides", Rate: 0}
export const ZONE_BAELSARS_WALL: ZoneObj = {Name: "Baelsar's Wall", Rate: 40}
export const ZONE_DUN_SCAITH: ZoneObj = {Name: "Dun Scaith", Rate: 58}
export const ZONE_LICHENWEED: ZoneObj = {Name: "Lichenweed", Rate: 0}
export const ZONE_SOHM_AL_HARD: ZoneObj = {Name: "Sohm Al (Hard)", Rate: 28}
export const ZONE_CONTAINMENT_BAY_Z1T9: ZoneObj = {Name: "Containment Bay Z1T9", Rate: 75}
export const ZONE_YANXIA: ZoneObj = {Name: "Yanxia", Rate: 84}
export const ZONE_OMEGA_CONTROL: ZoneObj = {Name: "Omega Control", Rate: 0}
export const ZONE_THE_DIADEM: ZoneObj = {Name: "The Diadem", Rate: 71}
export const ZONE_THE_SIRENSONG_SEA: ZoneObj = {Name: "The Sirensong Sea", Rate: 36}
export const ZONE_KUGANE_CASTLE: ZoneObj = {Name: "Kugane Castle", Rate: 0}
export const ZONE_THE_TEMPLE_OF_THE_FIST: ZoneObj = {Name: "The Temple of the Fist", Rate: 0}
export const ZONE_SHIROGANE: ZoneObj = {Name: "Shirogane", Rate: 82}
export const ZONE_RHALGRS_REACH: ZoneObj = {Name: "Rhalgr's Reach", Rate: 78}
export const ZONE_THE_FRINGES: ZoneObj = {Name: "The Fringes", Rate: 79}
export const ZONE_THE_PEAKS: ZoneObj = {Name: "The Peaks", Rate: 80}
export const ZONE_THE_LOCHS: ZoneObj = {Name: "The Lochs", Rate: 81}
export const ZONE_KUGANE: ZoneObj = {Name: "Kugane", Rate: 82}
export const ZONE_THE_RUBY_SEA: ZoneObj = {Name: "The Ruby Sea", Rate: 83}
export const ZONE_THE_AZIM_STEPPE: ZoneObj = {Name: "The Azim Steppe", Rate: 85}
export const ZONE_ALA_MHIGO: ZoneObj = {Name: "Ala Mhigo", Rate: 0}
export const ZONE_BARDAMS_METTLE: ZoneObj = {Name: "Bardam's Mettle", Rate: 0}
export const ZONE_THE_MISERY: ZoneObj = {Name: "The Misery", Rate: 36}
export const ZONE_RUBY_BAZAAR_OFFICES: ZoneObj = {Name: "Ruby Bazaar Offices", Rate: 0}
export const ZONE_THE_HOUSE_OF_THE_FIERCE: ZoneObj = {Name: "The House of the Fierce", Rate: 84}
export const ZONE_THE_DOMAN_ENCLAVE: ZoneObj = {Name: "The Doman Enclave", Rate: 84}
export const ZONE_BOKAIRO_INN: ZoneObj = {Name: "Bokairo Inn", Rate: 82}
export const ZONE_THE_FIRST_ALTAR_OF_DJANAN_QHAT: ZoneObj = {Name: "The First Altar of Djanan Qhat", Rate: 0}
export const ZONE_THE_RESONATORIUM: ZoneObj = {Name: "The Resonatorium", Rate: 0}
export const ZONE_THE_ROYAL_MENAGERIE: ZoneObj = {Name: "The Royal Menagerie", Rate: 0}
export const ZONE_KOBAI_GOTEN_APARTMENT_LOBBY: ZoneObj = {Name: "Kobai Goten Apartment Lobby", Rate: 0}
export const ZONE_THE_INTERDIMENSIONAL_RIFT: ZoneObj = {Name: "The Interdimensional Rift", Rate: 88}
export const ZONE_DELTASCAPE_V1: ZoneObj = {Name: "Deltascape V1.0", Rate: 88}
export const ZONE_DELTASCAPE_V2: ZoneObj = {Name: "Deltascape V2.0", Rate: 88}
export const ZONE_DELTASCAPE_V3: ZoneObj = {Name: "Deltascape V3.0", Rate: 88}
export const ZONE_DELTASCAPE_V4: ZoneObj = {Name: "Deltascape V4.0", Rate: 88}
export const ZONE_DOMA_CASTLE: ZoneObj = {Name: "Doma Castle", Rate: 0}
export const ZONE_CASTRUM_ABANIA: ZoneObj = {Name: "Castrum Abania", Rate: 0}
export const ZONE_EMANATION: ZoneObj = {Name: "Emanation", Rate: 87}
export const ZONE_THE_BLESSED_TREASURY: ZoneObj = {Name: "The Blessed Treasury", Rate: 77}
export const ZONE_THE_ROYAL_AIRSHIP_LANDING: ZoneObj = {Name: "The Royal Airship Landing", Rate: 76}
export const ZONE_TRANSPARENCY: ZoneObj = {Name: "Transparency", Rate: 76}
export const ZONE_THE_LOST_CANALS_OF_UZNAIR: ZoneObj = {Name: "The Lost Canals of Uznair", Rate: 0}
export const ZONE_ASTRAGALOS: ZoneObj = {Name: "Astragalos", Rate: 0}
export const ZONE_THE_DROWNED_CITY_OF_SKALLA: ZoneObj = {Name: "The Drowned City of Skalla", Rate: 0}
export const ZONE_EUREKA_ANEMOS: ZoneObj = {Name: "Eureka Anemos", Rate: 91}
export const ZONE_THE_BINDING_COIL_OF_BAHAMUT: ZoneObj = {Name: "The Binding Coil of Bahamut", Rate: 0}
export const ZONE_THE_HALL_OF_THE_GRIFFIN: ZoneObj = {Name: "The Hall of the Griffin", Rate: 0}
export const ZONE_THE_PRIMA_VISTA_TIRING_ROOM: ZoneObj = {Name: "The Prima Vista Tiring Room", Rate: 0}
export const ZONE_THE_PRIMA_VISTA_BRIDGE: ZoneObj = {Name: "The Prima Vista Bridge", Rate: 0}
export const ZONE_THE_ROYAL_CITY_OF_RABANASTRE: ZoneObj = {Name: "The Royal City of Rabanastre", Rate: 0}
export const ZONE_PRIVATE_COTTAGE__SHIROGANE: ZoneObj = {Name: "Private Cottage - Shirogane", Rate: 0}
export const ZONE_PRIVATE_HOUSE__SHIROGANE: ZoneObj = {Name: "Private House - Shirogane", Rate: 0}
export const ZONE_PRIVATE_MANSION__SHIROGANE: ZoneObj = {Name: "Private Mansion - Shirogane", Rate: 0}
export const ZONE_COMPANY_WORKSHOP__SHIROGANE: ZoneObj = {Name: "Company Workshop - Shirogane", Rate: 0}
export const ZONE_PRIVATE_CHAMBERS__SHIROGANE: ZoneObj = {Name: "Private Chambers - Shirogane", Rate: 0}
export const ZONE_MYTH: ZoneObj = {Name: "Myth", Rate: 76}
export const ZONE_KOBAI_GOTEN_APARTMENT: ZoneObj = {Name: "Kobai Goten Apartment", Rate: 0}
export const ZONE_HELLS_LID: ZoneObj = {Name: "Hells' Lid", Rate: 0}
export const ZONE_CRYSTAL_TOWER_TRAINING_GROUNDS: ZoneObj = {Name: "Crystal Tower Training Grounds", Rate: 0}
export const ZONE_THE_FRACTAL_CONTINUUM_HARD: ZoneObj = {Name: "The Fractal Continuum (Hard)", Rate: 0}
export const ZONE_SIGMASCAPE_V1: ZoneObj = {Name: "Sigmascape V1.0", Rate: 92}
export const ZONE_SIGMASCAPE_V2: ZoneObj = {Name: "Sigmascape V2.0", Rate: 92}
export const ZONE_SIGMASCAPE_V3: ZoneObj = {Name: "Sigmascape V3.0", Rate: 92}
export const ZONE_SIGMASCAPE_V4: ZoneObj = {Name: "Sigmascape V4.0", Rate: 92}
export const ZONE_THE_JADE_STOA: ZoneObj = {Name: "The Jade Stoa", Rate: 93}
export const ZONE_VALENTIONES_CEREMONY: ZoneObj = {Name: "Valentione's Ceremony", Rate: 0}
export const ZONE_KIENKAN: ZoneObj = {Name: "Kienkan", Rate: 0}
export const ZONE_REISEN_TEMPLE: ZoneObj = {Name: "Reisen Temple", Rate: 0}
export const ZONE_THE_SWALLOWS_COMPASS: ZoneObj = {Name: "The Swallow's Compass", Rate: 0}
export const ZONE_EUREKA_PAGOS: ZoneObj = {Name: "Eureka Pagos", Rate: 94}
export const ZONE_THE_GREAT_HUNT: ZoneObj = {Name: "The Great Hunt", Rate: 0}
export const ZONE_REISEN_TEMPLE_ROAD: ZoneObj = {Name: "Reisen Temple Road", Rate: 0}
export const ZONE_THE_RIDORANA_LIGHTHOUSE: ZoneObj = {Name: "The Ridorana Lighthouse", Rate: 0}
export const ZONE_ULTIMACY: ZoneObj = {Name: "Ultimacy", Rate: 26}
export const ZONE_CASTRUM_FLUMINIS: ZoneObj = {Name: "Castrum Fluminis", Rate: 0}
export const ZONE_HEAVENONHIGH: ZoneObj = {Name: "Heaven-on-High", Rate: 0}
export const ZONE_THE_BURN: ZoneObj = {Name: "The Burn", Rate: 0}
export const ZONE_SAINT_MOCIANNES_ARBORETUM_HARD: ZoneObj = {Name: "Saint Mocianne's Arboretum (Hard)", Rate: 0}
export const ZONE_THE_RIDORANA_CATARACT: ZoneObj = {Name: "The Ridorana Cataract", Rate: 0}
export const ZONE_EUREKA_PYROS: ZoneObj = {Name: "Eureka Pyros", Rate: 96}
export const ZONE_PSISCAPE_V1: ZoneObj = {Name: "Psiscape V1.0", Rate: 92}
export const ZONE_HIDDEN_GORGE: ZoneObj = {Name: "Hidden Gorge", Rate: 0}
export const ZONE_KUGANE_OHASHI: ZoneObj = {Name: "Kugane Ohashi", Rate: 0}
export const ZONE_BLUE_SKY: ZoneObj = {Name: "Blue Sky", Rate: 0}
export const ZONE_LAKELAND: ZoneObj = {Name: "Lakeland", Rate: 106}
export const ZONE_KHOLUSIA: ZoneObj = {Name: "Kholusia", Rate: 107}
export const ZONE_AMH_ARAENG: ZoneObj = {Name: "Amh Araeng", Rate: 108}
export const ZONE_IL_MHEG: ZoneObj = {Name: "Il Mheg", Rate: 109}
export const ZONE_THE_RAKTIKA_GREATWOOD: ZoneObj = {Name: "The Rak'tika Greatwood", Rate: 110}
export const ZONE_THE_TEMPEST: ZoneObj = {Name: "The Tempest", Rate: 111}
export const ZONE_THE_CRYSTARIUM: ZoneObj = {Name: "The Crystarium", Rate: 112}
export const ZONE_EULMORE: ZoneObj = {Name: "Eulmore", Rate: 113}
export const ZONE_THE_SHIFTING_ALTARS_OF_UZNAIR: ZoneObj = {Name: "The Shifting Altars of Uznair", Rate: 0}
export const ZONE_THE_GHIMLYT_DARK: ZoneObj = {Name: "The Ghimlyt Dark", Rate: 0}
export const ZONE_PSISCAPE_V2: ZoneObj = {Name: "Psiscape V2.0", Rate: 92}
export const ZONE_HELLS_KIER: ZoneObj = {Name: "Hells' Kier", Rate: 98}
export const ZONE_THE_HAUNTED_MANOR: ZoneObj = {Name: "The Haunted Manor", Rate: 0}
export const ZONE_THE_FALL_OF_BELAHDIA: ZoneObj = {Name: "The Fall of Belah'dia", Rate: 0}
export const ZONE_THE_QITANA_RAVEL: ZoneObj = {Name: "The Qitana Ravel", Rate: 102}
export const ZONE_THE_ORBONNE_MONASTERY: ZoneObj = {Name: "The Orbonne Monastery", Rate: 0}
export const ZONE_EUREKA_HYDATOS: ZoneObj = {Name: "Eureka Hydatos", Rate: 100}
export const ZONE_THE_WREATH_OF_SNAKES: ZoneObj = {Name: "The Wreath of Snakes", Rate: 99}
export const ZONE_GARLEAN_LEGION_TENTS: ZoneObj = {Name: "Garlean Legion Tents", Rate: 0}
export const ZONE_EORZEAN_ALLIANCE_HEADQUARTERS: ZoneObj = {Name: "Eorzean Alliance Headquarters", Rate: 0}
export const ZONE_DOHN_MHEG: ZoneObj = {Name: "Dohn Mheg", Rate: 0}
export const ZONE_THE_TWINNING: ZoneObj = {Name: "The Twinning", Rate: 0}
export const ZONE_AMAUROT: ZoneObj = {Name: "Amaurot", Rate: 105}
export const ZONE_MT_GULG: ZoneObj = {Name: "Mt. Gulg", Rate: 102}
export const ZONE_AKADAEMIA_ANYDER: ZoneObj = {Name: "Akadaemia Anyder", Rate: 0}
export const ZONE_MALIKAHS_WELL: ZoneObj = {Name: "Malikah's Well", Rate: 102}
export const ZONE_HOLMINSTER_SWITCH: ZoneObj = {Name: "Holminster Switch", Rate: 102}
export const ZONE_THE_SYRCUS_TRENCH: ZoneObj = {Name: "The Syrcus Trench", Rate: 0}
export const ZONE_THE_PENDANTS_PERSONAL_SUITE: ZoneObj = {Name: "The Pendants Personal Suite", Rate: 112}
export const ZONE_THE_OCULAR: ZoneObj = {Name: "The Ocular", Rate: 0}
export const ZONE_DUTIFUL_SISTERS_OF_THE_EDELWEISS: ZoneObj = {Name: "Dutiful Sisters of the Edelweiss", Rate: 15}
export const ZONE_DOCK_STOREHOUSE: ZoneObj = {Name: "Dock Storehouse", Rate: 18}
export const ZONE_THE_NABAATH_MINES: ZoneObj = {Name: "The Nabaath Mines", Rate: 108}
export const ZONE_RONKAN_REFLECTIONS: ZoneObj = {Name: "Ronkan Reflections", Rate: 110}
export const ZONE_THE_CROWN_OF_THE_IMMACULATE: ZoneObj = {Name: "The Crown of the Immaculate", Rate: 102}
export const ZONE_THE_CONFESSIONAL_OF_TOUPASA_THE_ELDER: ZoneObj = {Name: "The Confessional of Toupasa the Elder", Rate: 102}
export const ZONE_THE_DANCING_PLAGUE: ZoneObj = {Name: "The Dancing Plague", Rate: 103}
export const ZONE_THE_DYING_GASP: ZoneObj = {Name: "The Dying Gasp", Rate: 105}
export const ZONE_THE_CORE: ZoneObj = {Name: "The Core", Rate: 0}
export const ZONE_THE_HALO: ZoneObj = {Name: "The Halo", Rate: 0}
export const ZONE_THE_NEREUS_TRENCH: ZoneObj = {Name: "The Nereus Trench", Rate: 38}
export const ZONE_ATLAS_PEAK: ZoneObj = {Name: "Atlas Peak", Rate: 23}
export const ZONE_THE_DUNGEONS_OF_LYHE_GHIAH: ZoneObj = {Name: "The Dungeons of Lyhe Ghiah", Rate: 0}
export const ZONE_THE_EMPTY: ZoneObj = {Name: "The Empty", Rate: 0}
export const ZONE_THE_GRAND_COSMOS: ZoneObj = {Name: "The Grand Cosmos", Rate: 0}
export const ZONE_ONSAL_HAKAIR: ZoneObj = {Name: "Onsal Hakair", Rate: 117}
export const ZONE_THE_COPIED_FACTORY: ZoneObj = {Name: "The Copied Factory", Rate: 0}
export const ZONE_LIMINAL_SPACE: ZoneObj = {Name: "Liminal Space", Rate: 0}
export const ZONE_THE_FIRMAMENT: ZoneObj = {Name: "The Firmament", Rate: 47}
export const ZONE_EXCAVATION_TUNNELS: ZoneObj = {Name: "Excavation Tunnels", Rate: 0}
export const ZONE_LYHE_MHEG: ZoneObj = {Name: "Lyhe Mheg", Rate: 40}
export const ZONE_THE_IMPERIAL_PALACE: ZoneObj = {Name: "The Imperial Palace", Rate: 0}
export const ZONE_CINDER_DRIFT: ZoneObj = {Name: "Cinder Drift", Rate: 28}
export const ZONE_ANAMNESIS_ANYDER: ZoneObj = {Name: "Anamnesis Anyder", Rate: 0}
export const ZONE_THE_GANDOF_THUNDER_PLAINS: ZoneObj = {Name: "The Gandof Thunder Plains", Rate: 0}
export const ZONE_ASHFALL: ZoneObj = {Name: "Ashfall", Rate: 0}
export const ZONE_THE_HEROES_GAUNTLET: ZoneObj = {Name: "The Heroes' Gauntlet", Rate: 125}
export const ZONE_TRIALS_THRESHOLD: ZoneObj = {Name: "Trial's Threshold", Rate: 0}
export const ZONE_GREAT_GLACIER: ZoneObj = {Name: "Great Glacier", Rate: 46}
export const ZONE_CIDS_MEMORY: ZoneObj = {Name: "Cid's Memory", Rate: 123}
export const ZONE_THE_FALLING_CITY_OF_NYM: ZoneObj = {Name: "The Falling City of Nym", Rate: 0}
export const ZONE_FROZEN_REFLECTIONS: ZoneObj = {Name: "Frozen Reflections", Rate: 46}
export const ZONE_GANGOS: ZoneObj = {Name: "Gangos", Rate: 0}
export const ZONE_THE_ENDEAVOR: ZoneObj = {Name: "The Endeavor", Rate: 14}
export const ZONE_BOZJAN_SOUTHERN_FRONT: ZoneObj = {Name: "Bozjan Southern Front", Rate: 124}
export const ZONE_TRANSMISSION_CONTROL: ZoneObj = {Name: "Transmission Control", Rate: 123}
export const ZONE_THE_PUPPETS_BUNKER: ZoneObj = {Name: "The Puppets' Bunker", Rate: 0}
export const ZONE_THE_SEAT_OF_SACRIFICE: ZoneObj = {Name: "The Seat of Sacrifice", Rate: 125}
export const ZONE_THE_RIFT: ZoneObj = {Name: "The Rift", Rate: 125}
export const ZONE_ANOGGS_LAIR: ZoneObj = {Name: "Anogg's Lair", Rate: 0}
export const ZONE_CASTRUM_LACUS_LITORE: ZoneObj = {Name: "Castrum Lacus Litore", Rate: 124}
export const ZONE_TERNCLIFF: ZoneObj = {Name: "Terncliff", Rate: 0}
export const ZONE_TERNCLIFF_BAY: ZoneObj = {Name: "Terncliff Bay", Rate: 0}
export const ZONE_MATOYAS_RELICT: ZoneObj = {Name: "Matoya's Relict", Rate: 0}
export const ZONE_SPHERE_OF_NAUGHT: ZoneObj = {Name: "Sphere of Naught", Rate: 0}
export const ZONE_THE_GARDEN_OF_NOWHERE: ZoneObj = {Name: "The Garden of Nowhere", Rate: 0}
export const ZONE_LAXAN_LOFT: ZoneObj = {Name: "Laxan Loft", Rate: 0}
export const ZONE_CASTRUM_MARINUM_DRYDOCKS: ZoneObj = {Name: "Castrum Marinum Drydocks", Rate: 0}
export const ZONE_THE_SHIFTING_OUBLIETTES_OF_LYHE_GHIAH: ZoneObj = {Name: "The Shifting Oubliettes of Lyhe Ghiah", Rate: 0}
export const ZONE_DELUBRUM_REGINAE: ZoneObj = {Name: "Delubrum Reginae", Rate: 0}
export const ZONE_THE_LAST_TRACE: ZoneObj = {Name: "The Last Trace", Rate: 0}
export const ZONE_BYGONE_GAOL: ZoneObj = {Name: "Bygone Gaol", Rate: 0}
export const ZONE_THE_TOWER_AT_PARADIGMS_BREACH: ZoneObj = {Name: "The Tower at Paradigm's Breach", Rate: 0}
export const ZONE_ZADNOR: ZoneObj = {Name: "Zadnor", Rate: 130}
export const ZONE_PAGLTHAN: ZoneObj = {Name: "Paglth'an", Rate: 0}
export const ZONE_GSAVIOR_DECK: ZoneObj = {Name: "G-Savior Deck", Rate: 0}
export const ZONE_THE_DALRIADA: ZoneObj = {Name: "The Dalriada", Rate: 130}
export const ZONE_THE_DARK_INSIDE: ZoneObj = {Name: "The Dark Inside", Rate: 139}
export const ZONE_THE_MOTHERCRYSTAL: ZoneObj = {Name: "The Mothercrystal", Rate: 139}
export const ZONE_THE_FINAL_DAY: ZoneObj = {Name: "The Final Day", Rate: 116}
export const ZONE_EMPYREUM: ZoneObj = {Name: "Empyreum", Rate: 142}
export const ZONE_INGLESIDE_APARTMENT_LOBBY: ZoneObj = {Name: "Ingleside Apartment Lobby", Rate: 0}
export const ZONE_PRIVATE_COTTAGE__EMPYREUM: ZoneObj = {Name: "Private Cottage - Empyreum", Rate: 0}
export const ZONE_PRIVATE_HOUSE__EMPYREUM: ZoneObj = {Name: "Private House - Empyreum", Rate: 0}
export const ZONE_PRIVATE_MANSION__EMPYREUM: ZoneObj = {Name: "Private Mansion - Empyreum", Rate: 0}
export const ZONE_COMPANY_WORKSHOP__EMPYREUM: ZoneObj = {Name: "Company Workshop - Empyreum", Rate: 0}
export const ZONE_PRIVATE_CHAMBERS__EMPYREUM: ZoneObj = {Name: "Private Chambers - Empyreum", Rate: 0}
export const ZONE_INGLESIDE_APARTMENT: ZoneObj = {Name: "Ingleside Apartment", Rate: 0}
export const ZONE_OLD_SHARLAYAN: ZoneObj = {Name: "Old Sharlayan", Rate: 137}
export const ZONE_RADZATHAN: ZoneObj = {Name: "Radz-at-Han", Rate: 138}
export const ZONE_LABYRINTHOS: ZoneObj = {Name: "Labyrinthos", Rate: 131}
export const ZONE_THAVNAIR: ZoneObj = {Name: "Thavnair", Rate: 132}
export const ZONE_GARLEMALD: ZoneObj = {Name: "Garlemald", Rate: 133}
export const ZONE_MARE_LAMENTORUM: ZoneObj = {Name: "Mare Lamentorum", Rate: 135}
export const ZONE_ULTIMA_THULE: ZoneObj = {Name: "Ultima Thule", Rate: 136}
export const ZONE_ELPIS: ZoneObj = {Name: "Elpis", Rate: 134}
export const ZONE_THE_TOWER_OF_ZOT: ZoneObj = {Name: "The Tower of Zot", Rate: 0}
export const ZONE_THE_PHANTOMS_FEAST: ZoneObj = {Name: "The Phantoms' Feast", Rate: 0}
export const ZONE_SMILETON: ZoneObj = {Name: "Smileton", Rate: 0}
export const ZONE_THE_GATES_OF_PANDÆMONIUM: ZoneObj = {Name: "The Gates of Pandæmonium", Rate: 145}
export const ZONE_KTISIS_HYPERBOREIA: ZoneObj = {Name: "Ktisis Hyperboreia", Rate: 0}
export const ZONE_THE_STIGMA_DREAMSCAPE: ZoneObj = {Name: "The Stigma Dreamscape", Rate: 140}
export const ZONE_THE_AITIASCOPE: ZoneObj = {Name: "The Aitiascope", Rate: 0}
export const ZONE_THE_FERVID_LIMBO: ZoneObj = {Name: "The Fervid Limbo", Rate: 145}
export const ZONE_THE_TOWER_OF_BABIL: ZoneObj = {Name: "The Tower of Babil", Rate: 28}
export const ZONE_THE_EXCITATRON_6000: ZoneObj = {Name: "The Excitatron 6000", Rate: 0}
export const ZONE_THE_STAGNANT_LIMBO: ZoneObj = {Name: "The Stagnant Limbo", Rate: 145}
export const ZONE_THE_SANGUINE_LIMBO: ZoneObj = {Name: "The Sanguine Limbo", Rate: 145}
export const ZONE_THE_DEAD_ENDS: ZoneObj = {Name: "The Dead Ends", Rate: 144}
export const ZONE_VANASPATI: ZoneObj = {Name: "Vanaspati", Rate: 141}
export const ZONE_LEMURES_HEADQUARTERS: ZoneObj = {Name: "Lemures Headquarters", Rate: 0}
export const ZONE_MAIN_HALL: ZoneObj = {Name: "Main Hall", Rate: 137}
export const ZONE_ANDRON: ZoneObj = {Name: "Andron", Rate: 137}
export const ZONE_STRATEGY_ROOM: ZoneObj = {Name: "Strategy Room", Rate: 0}
export const ZONE_MAGNA_GLACIES: ZoneObj = {Name: "Magna Glacies", Rate: 0}
export const ZONE_BEYOND_THE_STARS: ZoneObj = {Name: "Beyond the Stars", Rate: 143}
export const ZONE_THE_NETHERGATE: ZoneObj = {Name: "The Nethergate", Rate: 0}
export const ZONE_PROPYLAION: ZoneObj = {Name: "Propylaion", Rate: 0}
export const ZONE_ALZADAALS_LEGACY: ZoneObj = {Name: "Alzadaal's Legacy", Rate: 0}
export const ZONE_AGLAIA: ZoneObj = {Name: "Aglaia", Rate: 147}
export const ZONE_MEDIAS_RES: ZoneObj = {Name: "Medias Res", Rate: 0}
export const ZONE_THE_PALAISTRA: ZoneObj = {Name: "The Palaistra", Rate: 0}
export const ZONE_THE_VOLCANIC_HEART: ZoneObj = {Name: "The Volcanic Heart", Rate: 0}
export const ZONE_THE_PORTA_DECUMANA: ZoneObj = {Name: "The Porta Decumana", Rate: 0}
export const ZONE_THE_OMPHALOS: ZoneObj = {Name: "The Omphalos", Rate: 147}
export const ZONE_RESTRICTED_ARCHIVES: ZoneObj = {Name: "Restricted Archives", Rate: 137}
export const ZONE_THE_FELL_COURT_OF_TROIA: ZoneObj = {Name: "The Fell Court of Troia", Rate: 149}
export const ZONE_THE_PESTILENT_PURGATORY: ZoneObj = {Name: "The Pestilent Purgatory", Rate: 145}
export const ZONE_UNNAMED_ISLAND: ZoneObj = {Name: "Unnamed Island", Rate: 148}
export const ZONE_ZEROS_DOMAIN: ZoneObj = {Name: "Zero's Domain", Rate: 149}
export const ZONE_MEGHADUTA_GUEST_CHAMBERS: ZoneObj = {Name: "Meghaduta Guest Chambers", Rate: 138}
export const ZONE_SNEAKY_HOLLOW: ZoneObj = {Name: "Sneaky Hollow", Rate: 0}
export const ZONE_STORMS_CROWN: ZoneObj = {Name: "Storm's Crown", Rate: 149}
export const ZONE_THE_HOLLOW_PURGATORY: ZoneObj = {Name: "The Hollow Purgatory", Rate: 145}
export const ZONE_ELYSION: ZoneObj = {Name: "Elysion", Rate: 136}
export const ZONE_THE_SILDIHN_SUBTERRANE: ZoneObj = {Name: "The Sil'dihn Subterrane", Rate: 0}
export const ZONE_ANOTHER_SILDIHN_SUBTERRANE: ZoneObj = {Name: "Another Sil'dihn Subterrane", Rate: 0}
export const ZONE_THE_CAUSTIC_PURGATORY: ZoneObj = {Name: "The Caustic Purgatory", Rate: 145}
export const ZONE_STYGIAN_INSENESCENCE_CELLS: ZoneObj = {Name: "Stygian Insenescence Cells", Rate: 145}
export const ZONE_EUPHROSYNE: ZoneObj = {Name: "Euphrosyne", Rate: 147}
export const ZONE_LAPIS_MANALIS: ZoneObj = {Name: "Lapis Manalis", Rate: 42}
export const ZONE_THE_SHIFTING_GYMNASION_AGONON: ZoneObj = {Name: "The Shifting Gymnasion Agonon", Rate: 0}
export const ZONE_SYLPHSTEP: ZoneObj = {Name: "Sylphstep", Rate: 0}
export const ZONE_EUREKA_ORTHOS: ZoneObj = {Name: "Eureka Orthos", Rate: 0}
export const ZONE_THE_CLOCKWORK_CASTLETOWN: ZoneObj = {Name: "The Clockwork Castletown", Rate: 0}
export const ZONE_MOUNT_ORDEALS: ZoneObj = {Name: "Mount Ordeals", Rate: 0}
export const ZONE_KHADGA: ZoneObj = {Name: "Khadga", Rate: 0}
export const ZONE_THE_VOIDCAST_DAIS: ZoneObj = {Name: "The Voidcast Dais", Rate: 149}
export const ZONE_THE_AETHERFONT: ZoneObj = {Name: "The Aetherfont", Rate: 0}
export const ZONE_THE_DÆMONS_NEST: ZoneObj = {Name: "The Dæmons' Nest", Rate: 145}
export const ZONE_ASCENSION: ZoneObj = {Name: "Ascension", Rate: 145}
export const ZONE_APEX_OF_CREATION: ZoneObj = {Name: "Apex of Creation", Rate: 145}
export const ZONE_THE_AETHERIAL_SLOUGH: ZoneObj = {Name: "The Aetherial Slough", Rate: 0}
export const ZONE_THE_GILDED_ARAYA: ZoneObj = {Name: "The Gilded Araya", Rate: 114}
export const ZONE_THE_CHAMBER_OF_FOURTEEN: ZoneObj = {Name: "The Chamber of Fourteen", Rate: 145}
export const ZONE_ESTINIENS_CHAMBERS: ZoneObj = {Name: "Estinien's Chambers", Rate: 138}
export const ZONE_SENATUS: ZoneObj = {Name: "Senatus", Rate: 133}
export const ZONE_THE_RED_MOON: ZoneObj = {Name: "The Red Moon", Rate: 149}
export const ZONE_MOUNT_ROKKON: ZoneObj = {Name: "Mount Rokkon", Rate: 0}
export const ZONE_ANOTHER_MOUNT_ROKKON: ZoneObj = {Name: "Another Mount Rokkon", Rate: 74}
export const ZONE_THE_RED_SANDS: ZoneObj = {Name: "The Red Sands", Rate: 0}
export const ZONE_TULIYOLLAL: ZoneObj = {Name: "Tuliyollal", Rate: 159}
export const ZONE_SOLUTION_NINE: ZoneObj = {Name: "Solution Nine", Rate: 163}
export const ZONE_URQOPACHA: ZoneObj = {Name: "Urqopacha", Rate: 160}
export const ZONE_KOZAMAUKA: ZoneObj = {Name: "Kozama'uka", Rate: 161}
export const ZONE_YAK_TEL: ZoneObj = {Name: "Yak T'el", Rate: 162}
export const ZONE_SHAALOANI: ZoneObj = {Name: "Shaaloani", Rate: 164}
export const ZONE_HERITAGE_FOUND: ZoneObj = {Name: "Heritage Found", Rate: 165}
export const ZONE_LIVING_MEMORY: ZoneObj = {Name: "Living Memory", Rate: 166}
export const ZONE_THE_LUNAR_SUBTERRANE: ZoneObj = {Name: "The Lunar Subterrane", Rate: 149}
export const ZONE_ALOALO_ISLAND: ZoneObj = {Name: "Aloalo Island", Rate: 0}
export const ZONE_ANOTHER_ALOALO_ISLAND: ZoneObj = {Name: "Another Aloalo Island", Rate: 0}
export const ZONE_BLUNDERVILLE: ZoneObj = {Name: "Blunderville", Rate: 0}
export const ZONE_THALEIA: ZoneObj = {Name: "Thaleia", Rate: 147}
export const ZONE_BLUNDERVILLE_SQUARE: ZoneObj = {Name: "Blunderville Square", Rate: 0}
export const ZONE_THE_ABYSSAL_FRACTURE: ZoneObj = {Name: "The Abyssal Fracture", Rate: 149}
export const ZONE_CENOTE_JA_JA_GURAL: ZoneObj = {Name: "Cenote Ja Ja Gural", Rate: 0}
export const ZONE_IHUYKATUMU: ZoneObj = {Name: "Ihuykatumu", Rate: 0}
export const ZONE_VANGUARD: ZoneObj = {Name: "Vanguard", Rate: 0}
export const ZONE_TENDER_VALLEY: ZoneObj = {Name: "Tender Valley", Rate: 0}
export const ZONE_WORQOR_ZORMOR: ZoneObj = {Name: "Worqor Zormor", Rate: 0}
export const ZONE_ORIGENICS: ZoneObj = {Name: "Origenics", Rate: 156}
export const ZONE_ALEXANDRIA: ZoneObj = {Name: "Alexandria", Rate: 157}
export const ZONE_THE_SKYDEEP_CENOTE: ZoneObj = {Name: "The Skydeep Cenote", Rate: 0}
export const ZONE_STRAYBOROUGH: ZoneObj = {Name: "Strayborough", Rate: 150}
export const ZONE_LOVELY_LOVERING: ZoneObj = {Name: "Lovely Lovering", Rate: 0}
export const ZONE_THE_THUNDERING: ZoneObj = {Name: "The Thundering", Rate: 0}
export const ZONE_WORQOR_LAR_DOR: ZoneObj = {Name: "Worqor Lar Dor", Rate: 0}
export const ZONE_BLASTING_RING: ZoneObj = {Name: "Blasting Ring", Rate: 0}
export const ZONE_SCRATCHING_RING: ZoneObj = {Name: "Scratching Ring", Rate: 0}
export const ZONE_INTERPHOS: ZoneObj = {Name: "Interphos", Rate: 157}
export const ZONE_SUMMIT_OF_EVERKEEP: ZoneObj = {Name: "Summit of Everkeep", Rate: 158}
export const ZONE_SUNPERCH: ZoneObj = {Name: "Sunperch", Rate: 159}
export const ZONE_EARTHEN_SKY_HIDEOUT: ZoneObj = {Name: "Earthen Sky Hideout", Rate: 165}
export const ZONE_MAIN_DECK: ZoneObj = {Name: "Main Deck", Rate: 0}
export const ZONE_THE_BACKROOM: ZoneObj = {Name: "The Backroom", Rate: 0}
export const ZONE_SKYDEEP_CENOTE_INNER_CHAMBER: ZoneObj = {Name: "Skydeep Cenote Inner Chamber", Rate: 0}
export const ZONE_TRITAILS_TRAINING: ZoneObj = {Name: "Tritails Training", Rate: 0}
export const ZONE_GREENROOM: ZoneObj = {Name: "Greenroom", Rate: 0}
export const ZONE_THE_FORARD_CABINS: ZoneObj = {Name: "The For'ard Cabins", Rate: 159}
export const ZONE_MANOR_BASEMENT: ZoneObj = {Name: "Manor Basement", Rate: 0}
export const ZONE_DREAMLIKE_PALACE: ZoneObj = {Name: "Dreamlike Palace", Rate: 0}
