export const ZONE_EORZEA = {Name: "Eorzea", Rate: 0}
export const ZONE_NEW_GRIDANIA = {Name: "New Gridania", Rate: 1}
export const ZONE_OLD_GRIDANIA = {Name: "Old Gridania", Rate: 2}
export const ZONE_CENTRAL_SHROUD = {Name: "Central Shroud", Rate: 3}
export const ZONE_EAST_SHROUD = {Name: "East Shroud", Rate: 4}
export const ZONE_SOUTH_SHROUD = {Name: "South Shroud", Rate: 5}
export const ZONE_NORTH_SHROUD = {Name: "North Shroud", Rate: 6}
export const ZONE_THE_TAMTARA_DEEPCROFT = {Name: "The Tam-Tara Deepcroft", Rate: 0}
export const ZONE_THE_THOUSAND_MAWS_OF_TOTORAK = {Name: "The Thousand Maws of Toto-Rak", Rate: 0}
export const ZONE_MORDION_GAOL = {Name: "Mordion Gaol", Rate: 0}
export const ZONE_LIMSA_LOMINSA_UPPER_DECKS = {Name: "Limsa Lominsa Upper Decks", Rate: 14}
export const ZONE_LIMSA_LOMINSA_LOWER_DECKS = {Name: "Limsa Lominsa Lower Decks", Rate: 15}
export const ZONE_ULDAH__STEPS_OF_NALD = {Name: "Ul'dah - Steps of Nald", Rate: 7}
export const ZONE_ULDAH__STEPS_OF_THAL = {Name: "Ul'dah - Steps of Thal", Rate: 8}
export const ZONE_MIDDLE_LA_NOSCEA = {Name: "Middle La Noscea", Rate: 16}
export const ZONE_LOWER_LA_NOSCEA = {Name: "Lower La Noscea", Rate: 17}
export const ZONE_EASTERN_LA_NOSCEA = {Name: "Eastern La Noscea", Rate: 18}
export const ZONE_WESTERN_LA_NOSCEA = {Name: "Western La Noscea", Rate: 19}
export const ZONE_UPPER_LA_NOSCEA = {Name: "Upper La Noscea", Rate: 20}
export const ZONE_WESTERN_THANALAN = {Name: "Western Thanalan", Rate: 9}
export const ZONE_CENTRAL_THANALAN = {Name: "Central Thanalan", Rate: 10}
export const ZONE_EASTERN_THANALAN = {Name: "Eastern Thanalan", Rate: 11}
export const ZONE_SOUTHERN_THANALAN = {Name: "Southern Thanalan", Rate: 12}
export const ZONE_NORTHERN_THANALAN = {Name: "Northern Thanalan", Rate: 13}
export const ZONE_MOR_DHONA = {Name: "Mor Dhona", Rate: 22}
export const ZONE_MIZZENMAST_INN = {Name: "Mizzenmast Inn", Rate: 0}
export const ZONE_THE_HOURGLASS = {Name: "The Hourglass", Rate: 0}
export const ZONE_THE_ROOST = {Name: "The Roost", Rate: 0}
export const ZONE_OUTER_LA_NOSCEA = {Name: "Outer La Noscea", Rate: 24}
export const ZONE_SASTASHA = {Name: "Sastasha", Rate: 0}
export const ZONE_THE_WANDERERS_PALACE = {Name: "The Wanderer's Palace", Rate: 0}
export const ZONE_THE_NAVEL = {Name: "The Navel", Rate: 23}
export const ZONE_COPPERBELL_MINES = {Name: "Copperbell Mines", Rate: 0}
export const ZONE_BOWL_OF_EMBERS = {Name: "Bowl of Embers", Rate: 25}
export const ZONE_THORNMARCH = {Name: "Thornmarch", Rate: 30}
export const ZONE_STONE_VIGIL = {Name: "Stone Vigil", Rate: 27}
export const ZONE_AURUM_VALE = {Name: "Aurum Vale", Rate: 0}
export const ZONE_THE_HOWLING_EYE = {Name: "The Howling Eye", Rate: 26}
export const ZONE_THE_SUNKEN_TEMPLE_OF_QARN = {Name: "The Sunken Temple of Qarn", Rate: 0}
export const ZONE_BRAYFLOXS_LONGSTOP = {Name: "Brayflox's Longstop", Rate: 0}
export const ZONE_HALATALI = {Name: "Halatali", Rate: 0}
export const ZONE_CASTRUM_MERIDIANUM = {Name: "Castrum Meridianum", Rate: 0}
export const ZONE_HAUKKE_MANOR = {Name: "Haukke Manor", Rate: 0}
export const ZONE_AMDAPOR_KEEP = {Name: "Amdapor Keep", Rate: 28}
export const ZONE_DZEMAEL_DARKHOLD = {Name: "Dzemael Darkhold", Rate: 0}
export const ZONE_WOLVES_DEN_PIER = {Name: "Wolves' Den Pier", Rate: 29}
export const ZONE_CUTTERS_CRY = {Name: "Cutter's Cry", Rate: 0}
export const ZONE_COERTHAS_CENTRAL_HIGHLANDS = {Name: "Coerthas Central Highlands", Rate: 21}
export const ZONE_THE_PRAETORIUM = {Name: "The Praetorium", Rate: 0}
export const ZONE_UPPER_AETHEROACOUSTIC_EXPLORATORY_SITE = {Name: "Upper Aetheroacoustic Exploratory Site", Rate: 0}
export const ZONE_LOWER_AETHEROACOUSTIC_EXPLORATORY_SITE = {Name: "Lower Aetheroacoustic Exploratory Site", Rate: 0}
export const ZONE_RAGNAROK_DRIVE_CYLINDER = {Name: "Ragnarok Drive Cylinder", Rate: 0}
export const ZONE_RAGNAROK_CENTRAL_CORE = {Name: "Ragnarok Central Core", Rate: 0}
export const ZONE_RAGNAROK_MAIN_BRIDGE = {Name: "Ragnarok Main Bridge", Rate: 0}
export const ZONE_THE_RAGNAROK = {Name: "The Ragnarok", Rate: 0}
export const ZONE_CENTRAL_DECKS = {Name: "Central Decks", Rate: 0}
export const ZONE_SEAT_OF_THE_FIRST_BOW = {Name: "Seat of the First Bow", Rate: 0}
export const ZONE_LOTUS_STAND = {Name: "Lotus Stand", Rate: 0}
export const ZONE_LABYRINTH_OF_THE_ANCIENTS = {Name: "Labyrinth of the Ancients", Rate: 0}
export const ZONE_MIST = {Name: "Mist", Rate: 32}
export const ZONE_COMMAND_ROOM = {Name: "Command Room", Rate: 14}
export const ZONE_THE_MEMORY_OF_EMBERS = {Name: "The Memory of Embers", Rate: 155}
export const ZONE_HEART_OF_THE_SWORN = {Name: "Heart of the Sworn", Rate: 0}
export const ZONE_THE_WAKING_SANDS = {Name: "The Waking Sands", Rate: 0}
export const ZONE_THE_FOLD = {Name: "The Fold", Rate: 0}
export const ZONE_THE_LAVENDER_BEDS = {Name: "The Lavender Beds", Rate: 34}
export const ZONE_THE_GOBLET = {Name: "The Goblet", Rate: 33}
export const ZONE_EORZEAN_SUBTERRANE = {Name: "Eorzean Subterrane", Rate: 0}
export const ZONE_PHAROS_SIRIUS = {Name: "Pharos Sirius", Rate: 28}
export const ZONE_PRIVATE_COTTAGE__MIST = {Name: "Private Cottage - Mist", Rate: 0}
export const ZONE_PRIVATE_HOUSE__MIST = {Name: "Private House - Mist", Rate: 0}
export const ZONE_PRIVATE_MANSION__MIST = {Name: "Private Mansion - Mist", Rate: 0}
export const ZONE_PRIVATE_COTTAGE__THE_LAVENDER_BEDS = {Name: "Private Cottage - The Lavender Beds", Rate: 0}
export const ZONE_PRIVATE_HOUSE__THE_LAVENDER_BEDS = {Name: "Private House - The Lavender Beds", Rate: 0}
export const ZONE_PRIVATE_MANSION__THE_LAVENDER_BEDS = {Name: "Private Mansion - The Lavender Beds", Rate: 0}
export const ZONE_PRIVATE_COTTAGE__THE_GOBLET = {Name: "Private Cottage - The Goblet", Rate: 0}
export const ZONE_PRIVATE_HOUSE__THE_GOBLET = {Name: "Private House - The Goblet", Rate: 0}
export const ZONE_PRIVATE_MANSION__THE_GOBLET = {Name: "Private Mansion - The Goblet", Rate: 0}
export const ZONE_THE_RISING_STONES = {Name: "The Rising Stones", Rate: 0}
export const ZONE_HAUKKE_MANOR_HARD = {Name: "Haukke Manor (Hard)", Rate: 0}
export const ZONE_COPPERBELL_MINES_HARD = {Name: "Copperbell Mines (Hard)", Rate: 0}
export const ZONE_PORTA_DECUMANA = {Name: "Porta Decumana", Rate: 31}
export const ZONE_GRIFFIN_CROSSING = {Name: "Griffin Crossing", Rate: 0}
export const ZONE_HALATALI_HARD = {Name: "Halatali (Hard)", Rate: 0}
export const ZONE_BRAYFLOXS_LONGSTOP_HARD = {Name: "Brayflox's Longstop (Hard)", Rate: 37}
export const ZONE_THE_WHORLEATER = {Name: "The Whorleater", Rate: 38}
export const ZONE_DALAMUDS_SHADOW = {Name: "Dalamud's Shadow", Rate: 0}
export const ZONE_THE_OUTER_COIL = {Name: "The Outer Coil", Rate: 28}
export const ZONE_THE_HOLOCHARTS = {Name: "The Holocharts", Rate: 0}
export const ZONE_THE_LOST_CITY_OF_AMDAPOR = {Name: "The Lost City of Amdapor", Rate: 40}
export const ZONE_THE_STONE_VIGIL_HARD = {Name: "The Stone Vigil (Hard)", Rate: 42}
export const ZONE_SYRCUS_TOWER = {Name: "Syrcus Tower", Rate: 0}
export const ZONE_THE_TAMTARA_DEEPCROFT_HARD = {Name: "The Tam-Tara Deepcroft (Hard)", Rate: 0}
export const ZONE_THE_STRIKING_TREE = {Name: "The Striking Tree", Rate: 43}
export const ZONE_CARTENEAU_FLATS_BORDERLAND_RUINS = {Name: "Carteneau Flats: Borderland Ruins", Rate: 0}
export const ZONE_HULLBREAKER_ISLE = {Name: "Hullbreaker Isle", Rate: 0}
export const ZONE_SASTASHA_HARD = {Name: "Sastasha (Hard)", Rate: 0}
export const ZONE_PRIVATE_CHAMBERS__MIST = {Name: "Private Chambers - Mist", Rate: 0}
export const ZONE_PRIVATE_CHAMBERS__THE_LAVENDER_BEDS = {Name: "Private Chambers - The Lavender Beds", Rate: 0}
export const ZONE_PRIVATE_CHAMBERS__THE_GOBLET = {Name: "Private Chambers - The Goblet", Rate: 0}
export const ZONE_AKH_AFAH_AMPHITHEATRE = {Name: "Akh Afah Amphitheatre", Rate: 46}
export const ZONE_SNOWCLOAK = {Name: "Snowcloak", Rate: 42}
export const ZONE_IC06_CENTRAL_DECKS = {Name: "IC-06 Central Decks", Rate: 0}
export const ZONE_IC06_REGENERATION_GRID = {Name: "IC-06 Regeneration Grid", Rate: 0}
export const ZONE_IC06_MAIN_BRIDGE = {Name: "IC-06 Main Bridge", Rate: 0}
export const ZONE_THE_BURNING_HEART = {Name: "The Burning Heart", Rate: 44}
export const ZONE_INTERCESSORY = {Name: "Intercessory", Rate: 0}
export const ZONE_THE_SUNKEN_TEMPLE_OF_QARN_HARD = {Name: "The Sunken Temple of Qarn (Hard)", Rate: 41}
export const ZONE_THE_WORLD_OF_DARKNESS = {Name: "The World of Darkness", Rate: 0}
export const ZONE_THE_BELLY_OF_THE_BEAST = {Name: "The Belly of the Beast", Rate: 0}
export const ZONE_STEPS_OF_FAITH = {Name: "Steps of Faith", Rate: 28}
export const ZONE_THE_WANDERERS_PALACE_HARD = {Name: "The Wanderer's Palace (Hard)", Rate: 40}
export const ZONE_AMDAPOR_KEEP_HARD = {Name: "Amdapor Keep (Hard)", Rate: 40}
export const ZONE_THE_GOLD_SAUCER = {Name: "The Gold Saucer", Rate: 0}
export const ZONE_CHOCOBO_SQUARE = {Name: "Chocobo Square", Rate: 0}
export const ZONE_THE_KEEPER_OF_THE_LAKE = {Name: "The Keeper of the Lake", Rate: 74}
export const ZONE_COMPANY_WORKSHOP__MIST = {Name: "Company Workshop - Mist", Rate: 0}
export const ZONE_COMPANY_WORKSHOP__THE_GOBLET = {Name: "Company Workshop - The Goblet", Rate: 0}
export const ZONE_COMPANY_WORKSHOP__THE_LAVENDER_BEDS = {Name: "Company Workshop - The Lavender Beds", Rate: 0}
export const ZONE_THE_CHRYSALIS = {Name: "The Chrysalis", Rate: 0}
export const ZONE_SANCTUM_OF_THE_TWELVE = {Name: "Sanctum of the Twelve", Rate: 4}
export const ZONE_COERTHAS_WESTERN_HIGHLANDS = {Name: "Coerthas Western Highlands", Rate: 49}
export const ZONE_THE_DRAVANIAN_FORELANDS = {Name: "The Dravanian Forelands", Rate: 50}
export const ZONE_THE_DRAVANIAN_HINTERLANDS = {Name: "The Dravanian Hinterlands", Rate: 51}
export const ZONE_THE_CHURNING_MISTS = {Name: "The Churning Mists", Rate: 52}
export const ZONE_THE_SEA_OF_CLOUDS = {Name: "The Sea of Clouds", Rate: 53}
export const ZONE_AZYS_LLA = {Name: "Azys Lla", Rate: 54}
export const ZONE_FOUNDATION = {Name: "Foundation", Rate: 47}
export const ZONE_THE_PILLARS = {Name: "The Pillars", Rate: 48}
export const ZONE_SAINT_ENDALIMS_SCHOLASTICATE = {Name: "Saint Endalim's Scholasticate", Rate: 0}
export const ZONE_SEAT_OF_THE_LORD_COMMANDER = {Name: "Seat of the Lord Commander", Rate: 0}
export const ZONE_FORTEMPS_MANOR = {Name: "Fortemps Manor", Rate: 0}
export const ZONE_CLOUD_NINE = {Name: "Cloud Nine", Rate: 0}
export const ZONE_THE_LIGHTFEATHER_PROVING_GROUNDS = {Name: "The Lightfeather Proving Grounds", Rate: 0}
export const ZONE_RULING_CHAMBER = {Name: "Ruling Chamber", Rate: 0}
export const ZONE_SACRIFICIAL_CHAMBER = {Name: "Sacrificial Chamber", Rate: 0}
export const ZONE_SOHM_AL_FOOTHILLS = {Name: "Sohm Al Foothills", Rate: 0}
export const ZONE_NEVERREAP = {Name: "Neverreap", Rate: 0}
export const ZONE_AETHEROCHEMICAL_RESEARCH_FACILITY = {Name: "Aetherochemical Research Facility", Rate: 0}
export const ZONE_THE_LIMITLESS_BLUE = {Name: "The Limitless Blue", Rate: 28}
export const ZONE_SINGULARITY_REACTOR = {Name: "Singularity Reactor", Rate: 56}
export const ZONE_THE_FIST_OF_THE_FATHER = {Name: "The Fist of the Father", Rate: 0}
export const ZONE_THE_CUFF_OF_THE_FATHER = {Name: "The Cuff of the Father", Rate: 0}
export const ZONE_THE_ARM_OF_THE_FATHER = {Name: "The Arm of the Father", Rate: 0}
export const ZONE_THE_BURDEN_OF_THE_FATHER = {Name: "The Burden of the Father", Rate: 0}
export const ZONE_THE_GREAT_GUBAL_LIBRARY = {Name: "The Great Gubal Library", Rate: 0}
export const ZONE_SEAL_ROCK = {Name: "Seal Rock", Rate: 59}
export const ZONE_DUSK_VIGIL = {Name: "Dusk Vigil", Rate: 42}
export const ZONE_THE_FRACTAL_CONTINUUM = {Name: "The Fractal Continuum", Rate: 0}
export const ZONE_THE_VAULT = {Name: "The Vault", Rate: 0}
export const ZONE_THE_AERY = {Name: "The Aery", Rate: 28}
export const ZONE_MATOYAS_CAVE = {Name: "Matoya's Cave", Rate: 0}
export const ZONE_THOK_AST_THOK = {Name: "Thok ast Thok", Rate: 57}
export const ZONE_IDYLLSHIRE = {Name: "Idyllshire", Rate: 55}
export const ZONE_THE_GORDIAN_KNOT = {Name: "The Gordian Knot", Rate: 0}
export const ZONE_CENTRAL_AZYS_LLA = {Name: "Central Azys Lla", Rate: 0}
export const ZONE_PHAROS_SIRIUS_HARD = {Name: "Pharos Sirius (Hard)", Rate: 28}
export const ZONE_THE_EIGHTEENTH_FLOOR = {Name: "The Eighteenth Floor", Rate: 0}
export const ZONE_SAINT_MOCIANNES_ARBORETUM = {Name: "Saint Mocianne's Arboretum", Rate: 0}
export const ZONE_VOID_ARK = {Name: "Void Ark", Rate: 37}
export const ZONE_THE_ANTITOWER = {Name: "The Antitower", Rate: 0}
export const ZONE_THE_LOST_CITY_OF_AMDAPOR_HARD = {Name: "The Lost City of Amdapor (Hard)", Rate: 63}
export const ZONE_CONTAINMENT_BAY_S1T7 = {Name: "Containment Bay S1T7", Rate: 66}
export const ZONE_THE_FEASTING_GROUNDS = {Name: "The Feasting Grounds", Rate: 0}
export const ZONE_THE_FIST_OF_THE_SON = {Name: "The Fist of the Son", Rate: 0}
export const ZONE_THE_CUFF_OF_THE_SON = {Name: "The Cuff of the Son", Rate: 0}
export const ZONE_THE_ARM_OF_THE_SON = {Name: "The Arm of the Son", Rate: 0}
export const ZONE_THE_BURDEN_OF_THE_SON = {Name: "The Burden of the Son", Rate: 0}
export const ZONE_THE_MIDAN_KNOT = {Name: "The Midan Knot", Rate: 0}
export const ZONE_SOHR_KHAI = {Name: "Sohr Khai", Rate: 0}
export const ZONE_THE_BATTLEHALL = {Name: "The Battlehall", Rate: 0}
export const ZONE_THE_FIELDS_OF_GLORY = {Name: "The Fields of Glory", Rate: 67}
export const ZONE_HULLBREAKER_ISLE_HARD = {Name: "Hullbreaker Isle (Hard)", Rate: 68}
export const ZONE_THE_WEEPING_CITY_OF_MHACH = {Name: "The Weeping City of Mhach", Rate: 0}
export const ZONE_THE_PARROCK = {Name: "The Parrock", Rate: 0}
export const ZONE_LEOFARDS_CHAMBERS = {Name: "Leofard's Chambers", Rate: 0}
export const ZONE_TWIN_ADDER_BARRACKS = {Name: "Twin Adder Barracks", Rate: 0}
export const ZONE_FLAME_BARRACKS = {Name: "Flame Barracks", Rate: 0}
export const ZONE_MAELSTROM_BARRACKS = {Name: "Maelstrom Barracks", Rate: 0}
export const ZONE_THE_GREAT_GUBAL_LIBRARY_HARD = {Name: "The Great Gubal Library (Hard)", Rate: 0}
export const ZONE_XELPHATOL = {Name: "Xelphatol", Rate: 40}
export const ZONE_THE_PALACE_OF_THE_DEAD = {Name: "The Palace of the Dead", Rate: 0}
export const ZONE_THE_AQUAPOLIS = {Name: "The Aquapolis", Rate: 0}
export const ZONE_LAST_REMNANT = {Name: "Last Remnant", Rate: 0}
export const ZONE_HAUNTED_MANOR = {Name: "Haunted Manor", Rate: 0}
export const ZONE_TOPMAST_APARTMENT_LOBBY = {Name: "Topmast Apartment Lobby", Rate: 0}
export const ZONE_LILY_HILLS_APARTMENT_LOBBY = {Name: "Lily Hills Apartment Lobby", Rate: 0}
export const ZONE_SULTANAS_BREATH_APARTMENT_LOBBY = {Name: "Sultana's Breath Apartment Lobby", Rate: 0}
export const ZONE_TOPMAST_APARTMENT = {Name: "Topmast Apartment", Rate: 0}
export const ZONE_LILY_HILLS_APARTMENT = {Name: "Lily Hills Apartment", Rate: 0}
export const ZONE_SULTANAS_BREATH_APARTMENT = {Name: "Sultana's Breath Apartment", Rate: 0}
export const ZONE_EYES_OF_THE_CREATOR = {Name: "Eyes of the Creator", Rate: 0}
export const ZONE_BREATH_OF_THE_CREATOR = {Name: "Breath of the Creator", Rate: 0}
export const ZONE_HEART_OF_THE_CREATOR = {Name: "Heart of the Creator", Rate: 0}
export const ZONE_SOUL_OF_THE_CREATOR = {Name: "Soul of the Creator", Rate: 0}
export const ZONE_CONTAINMENT_BAY_P1T6 = {Name: "Containment Bay P1T6", Rate: 69}
export const ZONE_FRONDALES_HOME_FOR_FRIENDLESS_FOUNDLINGS = {Name: "Frondale's Home for Friendless Foundlings", Rate: 0}
export const ZONE_SHISUI_OF_THE_VIOLET_TIDES = {Name: "Shisui of the Violet Tides", Rate: 0}
export const ZONE_BAELSARS_WALL = {Name: "Baelsar's Wall", Rate: 40}
export const ZONE_DUN_SCAITH = {Name: "Dun Scaith", Rate: 58}
export const ZONE_LICHENWEED = {Name: "Lichenweed", Rate: 0}
export const ZONE_SOHM_AL_HARD = {Name: "Sohm Al (Hard)", Rate: 28}
export const ZONE_CONTAINMENT_BAY_Z1T9 = {Name: "Containment Bay Z1T9", Rate: 75}
export const ZONE_YANXIA = {Name: "Yanxia", Rate: 84}
export const ZONE_OMEGA_CONTROL = {Name: "Omega Control", Rate: 0}
export const ZONE_THE_DIADEM = {Name: "The Diadem", Rate: 71}
export const ZONE_THE_SIRENSONG_SEA = {Name: "The Sirensong Sea", Rate: 36}
export const ZONE_KUGANE_CASTLE = {Name: "Kugane Castle", Rate: 0}
export const ZONE_THE_TEMPLE_OF_THE_FIST = {Name: "The Temple of the Fist", Rate: 0}
export const ZONE_SHIROGANE = {Name: "Shirogane", Rate: 82}
export const ZONE_RHALGRS_REACH = {Name: "Rhalgr's Reach", Rate: 78}
export const ZONE_THE_FRINGES = {Name: "The Fringes", Rate: 79}
export const ZONE_THE_PEAKS = {Name: "The Peaks", Rate: 80}
export const ZONE_THE_LOCHS = {Name: "The Lochs", Rate: 81}
export const ZONE_KUGANE = {Name: "Kugane", Rate: 82}
export const ZONE_THE_RUBY_SEA = {Name: "The Ruby Sea", Rate: 83}
export const ZONE_THE_AZIM_STEPPE = {Name: "The Azim Steppe", Rate: 85}
export const ZONE_ALA_MHIGO = {Name: "Ala Mhigo", Rate: 0}
export const ZONE_BARDAMS_METTLE = {Name: "Bardam's Mettle", Rate: 0}
export const ZONE_THE_MISERY = {Name: "The Misery", Rate: 36}
export const ZONE_RUBY_BAZAAR_OFFICES = {Name: "Ruby Bazaar Offices", Rate: 0}
export const ZONE_THE_HOUSE_OF_THE_FIERCE = {Name: "The House of the Fierce", Rate: 84}
export const ZONE_THE_DOMAN_ENCLAVE = {Name: "The Doman Enclave", Rate: 84}
export const ZONE_BOKAIRO_INN = {Name: "Bokairo Inn", Rate: 82}
export const ZONE_THE_FIRST_ALTAR_OF_DJANAN_QHAT = {Name: "The First Altar of Djanan Qhat", Rate: 0}
export const ZONE_THE_RESONATORIUM = {Name: "The Resonatorium", Rate: 0}
export const ZONE_THE_ROYAL_MENAGERIE = {Name: "The Royal Menagerie", Rate: 0}
export const ZONE_KOBAI_GOTEN_APARTMENT_LOBBY = {Name: "Kobai Goten Apartment Lobby", Rate: 0}
export const ZONE_THE_INTERDIMENSIONAL_RIFT = {Name: "The Interdimensional Rift", Rate: 88}
export const ZONE_DELTASCAPE_V1 = {Name: "Deltascape V1.0", Rate: 88}
export const ZONE_DELTASCAPE_V2 = {Name: "Deltascape V2.0", Rate: 88}
export const ZONE_DELTASCAPE_V3 = {Name: "Deltascape V3.0", Rate: 88}
export const ZONE_DELTASCAPE_V4 = {Name: "Deltascape V4.0", Rate: 88}
export const ZONE_DOMA_CASTLE = {Name: "Doma Castle", Rate: 0}
export const ZONE_CASTRUM_ABANIA = {Name: "Castrum Abania", Rate: 0}
export const ZONE_EMANATION = {Name: "Emanation", Rate: 87}
export const ZONE_THE_BLESSED_TREASURY = {Name: "The Blessed Treasury", Rate: 77}
export const ZONE_THE_ROYAL_AIRSHIP_LANDING = {Name: "The Royal Airship Landing", Rate: 76}
export const ZONE_TRANSPARENCY = {Name: "Transparency", Rate: 76}
export const ZONE_THE_LOST_CANALS_OF_UZNAIR = {Name: "The Lost Canals of Uznair", Rate: 0}
export const ZONE_ASTRAGALOS = {Name: "Astragalos", Rate: 0}
export const ZONE_THE_DROWNED_CITY_OF_SKALLA = {Name: "The Drowned City of Skalla", Rate: 0}
export const ZONE_EUREKA_ANEMOS = {Name: "Eureka Anemos", Rate: 91}
export const ZONE_THE_BINDING_COIL_OF_BAHAMUT = {Name: "The Binding Coil of Bahamut", Rate: 0}
export const ZONE_THE_HALL_OF_THE_GRIFFIN = {Name: "The Hall of the Griffin", Rate: 0}
export const ZONE_THE_PRIMA_VISTA_TIRING_ROOM = {Name: "The Prima Vista Tiring Room", Rate: 0}
export const ZONE_THE_PRIMA_VISTA_BRIDGE = {Name: "The Prima Vista Bridge", Rate: 0}
export const ZONE_THE_ROYAL_CITY_OF_RABANASTRE = {Name: "The Royal City of Rabanastre", Rate: 0}
export const ZONE_PRIVATE_COTTAGE__SHIROGANE = {Name: "Private Cottage - Shirogane", Rate: 0}
export const ZONE_PRIVATE_HOUSE__SHIROGANE = {Name: "Private House - Shirogane", Rate: 0}
export const ZONE_PRIVATE_MANSION__SHIROGANE = {Name: "Private Mansion - Shirogane", Rate: 0}
export const ZONE_COMPANY_WORKSHOP__SHIROGANE = {Name: "Company Workshop - Shirogane", Rate: 0}
export const ZONE_PRIVATE_CHAMBERS__SHIROGANE = {Name: "Private Chambers - Shirogane", Rate: 0}
export const ZONE_MYTH = {Name: "Myth", Rate: 76}
export const ZONE_KOBAI_GOTEN_APARTMENT = {Name: "Kobai Goten Apartment", Rate: 0}
export const ZONE_HELLS_LID = {Name: "Hells' Lid", Rate: 0}
export const ZONE_CRYSTAL_TOWER_TRAINING_GROUNDS = {Name: "Crystal Tower Training Grounds", Rate: 0}
export const ZONE_THE_FRACTAL_CONTINUUM_HARD = {Name: "The Fractal Continuum (Hard)", Rate: 0}
export const ZONE_SIGMASCAPE_V1 = {Name: "Sigmascape V1.0", Rate: 92}
export const ZONE_SIGMASCAPE_V2 = {Name: "Sigmascape V2.0", Rate: 92}
export const ZONE_SIGMASCAPE_V3 = {Name: "Sigmascape V3.0", Rate: 92}
export const ZONE_SIGMASCAPE_V4 = {Name: "Sigmascape V4.0", Rate: 92}
export const ZONE_THE_JADE_STOA = {Name: "The Jade Stoa", Rate: 93}
export const ZONE_VALENTIONES_CEREMONY = {Name: "Valentione's Ceremony", Rate: 0}
export const ZONE_KIENKAN = {Name: "Kienkan", Rate: 0}
export const ZONE_REISEN_TEMPLE = {Name: "Reisen Temple", Rate: 0}
export const ZONE_THE_SWALLOWS_COMPASS = {Name: "The Swallow's Compass", Rate: 0}
export const ZONE_EUREKA_PAGOS = {Name: "Eureka Pagos", Rate: 94}
export const ZONE_THE_GREAT_HUNT = {Name: "The Great Hunt", Rate: 0}
export const ZONE_REISEN_TEMPLE_ROAD = {Name: "Reisen Temple Road", Rate: 0}
export const ZONE_THE_RIDORANA_LIGHTHOUSE = {Name: "The Ridorana Lighthouse", Rate: 0}
export const ZONE_ULTIMACY = {Name: "Ultimacy", Rate: 26}
export const ZONE_CASTRUM_FLUMINIS = {Name: "Castrum Fluminis", Rate: 0}
export const ZONE_HEAVENONHIGH = {Name: "Heaven-on-High", Rate: 0}
export const ZONE_THE_BURN = {Name: "The Burn", Rate: 0}
export const ZONE_SAINT_MOCIANNES_ARBORETUM_HARD = {Name: "Saint Mocianne's Arboretum (Hard)", Rate: 0}
export const ZONE_THE_RIDORANA_CATARACT = {Name: "The Ridorana Cataract", Rate: 0}
export const ZONE_EUREKA_PYROS = {Name: "Eureka Pyros", Rate: 96}
export const ZONE_PSISCAPE_V1 = {Name: "Psiscape V1.0", Rate: 92}
export const ZONE_HIDDEN_GORGE = {Name: "Hidden Gorge", Rate: 0}
export const ZONE_KUGANE_OHASHI = {Name: "Kugane Ohashi", Rate: 0}
export const ZONE_BLUE_SKY = {Name: "Blue Sky", Rate: 0}
export const ZONE_LAKELAND = {Name: "Lakeland", Rate: 106}
export const ZONE_KHOLUSIA = {Name: "Kholusia", Rate: 107}
export const ZONE_AMH_ARAENG = {Name: "Amh Araeng", Rate: 108}
export const ZONE_IL_MHEG = {Name: "Il Mheg", Rate: 109}
export const ZONE_THE_RAKTIKA_GREATWOOD = {Name: "The Rak'tika Greatwood", Rate: 110}
export const ZONE_THE_TEMPEST = {Name: "The Tempest", Rate: 111}
export const ZONE_THE_CRYSTARIUM = {Name: "The Crystarium", Rate: 112}
export const ZONE_EULMORE = {Name: "Eulmore", Rate: 113}
export const ZONE_THE_SHIFTING_ALTARS_OF_UZNAIR = {Name: "The Shifting Altars of Uznair", Rate: 0}
export const ZONE_THE_GHIMLYT_DARK = {Name: "The Ghimlyt Dark", Rate: 0}
export const ZONE_PSISCAPE_V2 = {Name: "Psiscape V2.0", Rate: 92}
export const ZONE_HELLS_KIER = {Name: "Hells' Kier", Rate: 98}
export const ZONE_THE_HAUNTED_MANOR = {Name: "The Haunted Manor", Rate: 0}
export const ZONE_THE_FALL_OF_BELAHDIA = {Name: "The Fall of Belah'dia", Rate: 0}
export const ZONE_THE_QITANA_RAVEL = {Name: "The Qitana Ravel", Rate: 102}
export const ZONE_THE_ORBONNE_MONASTERY = {Name: "The Orbonne Monastery", Rate: 0}
export const ZONE_EUREKA_HYDATOS = {Name: "Eureka Hydatos", Rate: 100}
export const ZONE_THE_WREATH_OF_SNAKES = {Name: "The Wreath of Snakes", Rate: 99}
export const ZONE_GARLEAN_LEGION_TENTS = {Name: "Garlean Legion Tents", Rate: 0}
export const ZONE_EORZEAN_ALLIANCE_HEADQUARTERS = {Name: "Eorzean Alliance Headquarters", Rate: 0}
export const ZONE_DOHN_MHEG = {Name: "Dohn Mheg", Rate: 0}
export const ZONE_THE_TWINNING = {Name: "The Twinning", Rate: 0}
export const ZONE_AMAUROT = {Name: "Amaurot", Rate: 105}
export const ZONE_MT_GULG = {Name: "Mt. Gulg", Rate: 102}
export const ZONE_AKADAEMIA_ANYDER = {Name: "Akadaemia Anyder", Rate: 0}
export const ZONE_MALIKAHS_WELL = {Name: "Malikah's Well", Rate: 102}
export const ZONE_HOLMINSTER_SWITCH = {Name: "Holminster Switch", Rate: 102}
export const ZONE_THE_SYRCUS_TRENCH = {Name: "The Syrcus Trench", Rate: 0}
export const ZONE_THE_PENDANTS_PERSONAL_SUITE = {Name: "The Pendants Personal Suite", Rate: 112}
export const ZONE_THE_OCULAR = {Name: "The Ocular", Rate: 0}
export const ZONE_DUTIFUL_SISTERS_OF_THE_EDELWEISS = {Name: "Dutiful Sisters of the Edelweiss", Rate: 15}
export const ZONE_DOCK_STOREHOUSE = {Name: "Dock Storehouse", Rate: 18}
export const ZONE_THE_NABAATH_MINES = {Name: "The Nabaath Mines", Rate: 108}
export const ZONE_RONKAN_REFLECTIONS = {Name: "Ronkan Reflections", Rate: 110}
export const ZONE_THE_CROWN_OF_THE_IMMACULATE = {Name: "The Crown of the Immaculate", Rate: 102}
export const ZONE_THE_CONFESSIONAL_OF_TOUPASA_THE_ELDER = {Name: "The Confessional of Toupasa the Elder", Rate: 102}
export const ZONE_THE_DANCING_PLAGUE = {Name: "The Dancing Plague", Rate: 103}
export const ZONE_THE_DYING_GASP = {Name: "The Dying Gasp", Rate: 105}
export const ZONE_THE_CORE = {Name: "The Core", Rate: 0}
export const ZONE_THE_HALO = {Name: "The Halo", Rate: 0}
export const ZONE_THE_NEREUS_TRENCH = {Name: "The Nereus Trench", Rate: 38}
export const ZONE_ATLAS_PEAK = {Name: "Atlas Peak", Rate: 23}
export const ZONE_THE_DUNGEONS_OF_LYHE_GHIAH = {Name: "The Dungeons of Lyhe Ghiah", Rate: 0}
export const ZONE_THE_EMPTY = {Name: "The Empty", Rate: 0}
export const ZONE_THE_GRAND_COSMOS = {Name: "The Grand Cosmos", Rate: 0}
export const ZONE_ONSAL_HAKAIR = {Name: "Onsal Hakair", Rate: 117}
export const ZONE_THE_COPIED_FACTORY = {Name: "The Copied Factory", Rate: 0}
export const ZONE_LIMINAL_SPACE = {Name: "Liminal Space", Rate: 0}
export const ZONE_THE_FIRMAMENT = {Name: "The Firmament", Rate: 47}
export const ZONE_EXCAVATION_TUNNELS = {Name: "Excavation Tunnels", Rate: 0}
export const ZONE_LYHE_MHEG = {Name: "Lyhe Mheg", Rate: 40}
export const ZONE_THE_IMPERIAL_PALACE = {Name: "The Imperial Palace", Rate: 0}
export const ZONE_CINDER_DRIFT = {Name: "Cinder Drift", Rate: 28}
export const ZONE_ANAMNESIS_ANYDER = {Name: "Anamnesis Anyder", Rate: 0}
export const ZONE_THE_GANDOF_THUNDER_PLAINS = {Name: "The Gandof Thunder Plains", Rate: 0}
export const ZONE_ASHFALL = {Name: "Ashfall", Rate: 0}
export const ZONE_THE_HEROES_GAUNTLET = {Name: "The Heroes' Gauntlet", Rate: 125}
export const ZONE_TRIALS_THRESHOLD = {Name: "Trial's Threshold", Rate: 0}
export const ZONE_GREAT_GLACIER = {Name: "Great Glacier", Rate: 46}
export const ZONE_CIDS_MEMORY = {Name: "Cid's Memory", Rate: 123}
export const ZONE_THE_FALLING_CITY_OF_NYM = {Name: "The Falling City of Nym", Rate: 0}
export const ZONE_FROZEN_REFLECTIONS = {Name: "Frozen Reflections", Rate: 46}
export const ZONE_GANGOS = {Name: "Gangos", Rate: 0}
export const ZONE_THE_ENDEAVOR = {Name: "The Endeavor", Rate: 14}
export const ZONE_BOZJAN_SOUTHERN_FRONT = {Name: "Bozjan Southern Front", Rate: 124}
export const ZONE_TRANSMISSION_CONTROL = {Name: "Transmission Control", Rate: 123}
export const ZONE_THE_PUPPETS_BUNKER = {Name: "The Puppets' Bunker", Rate: 0}
export const ZONE_THE_SEAT_OF_SACRIFICE = {Name: "The Seat of Sacrifice", Rate: 125}
export const ZONE_THE_RIFT = {Name: "The Rift", Rate: 125}
export const ZONE_ANOGGS_LAIR = {Name: "Anogg's Lair", Rate: 0}
export const ZONE_CASTRUM_LACUS_LITORE = {Name: "Castrum Lacus Litore", Rate: 124}
export const ZONE_TERNCLIFF = {Name: "Terncliff", Rate: 0}
export const ZONE_TERNCLIFF_BAY = {Name: "Terncliff Bay", Rate: 0}
export const ZONE_MATOYAS_RELICT = {Name: "Matoya's Relict", Rate: 0}
export const ZONE_SPHERE_OF_NAUGHT = {Name: "Sphere of Naught", Rate: 0}
export const ZONE_THE_GARDEN_OF_NOWHERE = {Name: "The Garden of Nowhere", Rate: 0}
export const ZONE_LAXAN_LOFT = {Name: "Laxan Loft", Rate: 0}
export const ZONE_CASTRUM_MARINUM_DRYDOCKS = {Name: "Castrum Marinum Drydocks", Rate: 0}
export const ZONE_THE_SHIFTING_OUBLIETTES_OF_LYHE_GHIAH = {Name: "The Shifting Oubliettes of Lyhe Ghiah", Rate: 0}
export const ZONE_DELUBRUM_REGINAE = {Name: "Delubrum Reginae", Rate: 0}
export const ZONE_THE_LAST_TRACE = {Name: "The Last Trace", Rate: 0}
export const ZONE_BYGONE_GAOL = {Name: "Bygone Gaol", Rate: 0}
export const ZONE_THE_TOWER_AT_PARADIGMS_BREACH = {Name: "The Tower at Paradigm's Breach", Rate: 0}
export const ZONE_ZADNOR = {Name: "Zadnor", Rate: 130}
export const ZONE_PAGLTHAN = {Name: "Paglth'an", Rate: 0}
export const ZONE_GSAVIOR_DECK = {Name: "G-Savior Deck", Rate: 0}
export const ZONE_THE_DALRIADA = {Name: "The Dalriada", Rate: 130}
export const ZONE_THE_DARK_INSIDE = {Name: "The Dark Inside", Rate: 139}
export const ZONE_THE_MOTHERCRYSTAL = {Name: "The Mothercrystal", Rate: 139}
export const ZONE_THE_FINAL_DAY = {Name: "The Final Day", Rate: 116}
export const ZONE_EMPYREUM = {Name: "Empyreum", Rate: 142}
export const ZONE_INGLESIDE_APARTMENT_LOBBY = {Name: "Ingleside Apartment Lobby", Rate: 0}
export const ZONE_PRIVATE_COTTAGE__EMPYREUM = {Name: "Private Cottage - Empyreum", Rate: 0}
export const ZONE_PRIVATE_HOUSE__EMPYREUM = {Name: "Private House - Empyreum", Rate: 0}
export const ZONE_PRIVATE_MANSION__EMPYREUM = {Name: "Private Mansion - Empyreum", Rate: 0}
export const ZONE_COMPANY_WORKSHOP__EMPYREUM = {Name: "Company Workshop - Empyreum", Rate: 0}
export const ZONE_PRIVATE_CHAMBERS__EMPYREUM = {Name: "Private Chambers - Empyreum", Rate: 0}
export const ZONE_INGLESIDE_APARTMENT = {Name: "Ingleside Apartment", Rate: 0}
export const ZONE_OLD_SHARLAYAN = {Name: "Old Sharlayan", Rate: 137}
export const ZONE_RADZATHAN = {Name: "Radz-at-Han", Rate: 138}
export const ZONE_LABYRINTHOS = {Name: "Labyrinthos", Rate: 131}
export const ZONE_THAVNAIR = {Name: "Thavnair", Rate: 132}
export const ZONE_GARLEMALD = {Name: "Garlemald", Rate: 133}
export const ZONE_MARE_LAMENTORUM = {Name: "Mare Lamentorum", Rate: 135}
export const ZONE_ULTIMA_THULE = {Name: "Ultima Thule", Rate: 136}
export const ZONE_ELPIS = {Name: "Elpis", Rate: 134}
export const ZONE_THE_TOWER_OF_ZOT = {Name: "The Tower of Zot", Rate: 0}
export const ZONE_THE_PHANTOMS_FEAST = {Name: "The Phantoms' Feast", Rate: 0}
export const ZONE_SMILETON = {Name: "Smileton", Rate: 0}
export const ZONE_THE_GATES_OF_PANDÆMONIUM = {Name: "The Gates of Pandæmonium", Rate: 145}
export const ZONE_KTISIS_HYPERBOREIA = {Name: "Ktisis Hyperboreia", Rate: 0}
export const ZONE_THE_STIGMA_DREAMSCAPE = {Name: "The Stigma Dreamscape", Rate: 140}
export const ZONE_THE_AITIASCOPE = {Name: "The Aitiascope", Rate: 0}
export const ZONE_THE_FERVID_LIMBO = {Name: "The Fervid Limbo", Rate: 145}
export const ZONE_THE_TOWER_OF_BABIL = {Name: "The Tower of Babil", Rate: 28}
export const ZONE_THE_EXCITATRON_6000 = {Name: "The Excitatron 6000", Rate: 0}
export const ZONE_THE_STAGNANT_LIMBO = {Name: "The Stagnant Limbo", Rate: 145}
export const ZONE_THE_SANGUINE_LIMBO = {Name: "The Sanguine Limbo", Rate: 145}
export const ZONE_THE_DEAD_ENDS = {Name: "The Dead Ends", Rate: 144}
export const ZONE_VANASPATI = {Name: "Vanaspati", Rate: 141}
export const ZONE_LEMURES_HEADQUARTERS = {Name: "Lemures Headquarters", Rate: 0}
export const ZONE_MAIN_HALL = {Name: "Main Hall", Rate: 137}
export const ZONE_ANDRON = {Name: "Andron", Rate: 137}
export const ZONE_STRATEGY_ROOM = {Name: "Strategy Room", Rate: 0}
export const ZONE_MAGNA_GLACIES = {Name: "Magna Glacies", Rate: 0}
export const ZONE_BEYOND_THE_STARS = {Name: "Beyond the Stars", Rate: 143}
export const ZONE_THE_NETHERGATE = {Name: "The Nethergate", Rate: 0}
export const ZONE_PROPYLAION = {Name: "Propylaion", Rate: 0}
export const ZONE_ALZADAALS_LEGACY = {Name: "Alzadaal's Legacy", Rate: 0}
export const ZONE_AGLAIA = {Name: "Aglaia", Rate: 147}
export const ZONE_MEDIAS_RES = {Name: "Medias Res", Rate: 0}
export const ZONE_THE_PALAISTRA = {Name: "The Palaistra", Rate: 0}
export const ZONE_THE_VOLCANIC_HEART = {Name: "The Volcanic Heart", Rate: 0}
export const ZONE_THE_PORTA_DECUMANA = {Name: "The Porta Decumana", Rate: 0}
export const ZONE_THE_OMPHALOS = {Name: "The Omphalos", Rate: 147}
export const ZONE_RESTRICTED_ARCHIVES = {Name: "Restricted Archives", Rate: 137}
export const ZONE_THE_FELL_COURT_OF_TROIA = {Name: "The Fell Court of Troia", Rate: 149}
export const ZONE_THE_PESTILENT_PURGATORY = {Name: "The Pestilent Purgatory", Rate: 145}
export const ZONE_UNNAMED_ISLAND = {Name: "Unnamed Island", Rate: 148}
export const ZONE_ZEROS_DOMAIN = {Name: "Zero's Domain", Rate: 149}
export const ZONE_MEGHADUTA_GUEST_CHAMBERS = {Name: "Meghaduta Guest Chambers", Rate: 138}
export const ZONE_SNEAKY_HOLLOW = {Name: "Sneaky Hollow", Rate: 0}
export const ZONE_STORMS_CROWN = {Name: "Storm's Crown", Rate: 149}
export const ZONE_THE_HOLLOW_PURGATORY = {Name: "The Hollow Purgatory", Rate: 145}
export const ZONE_ELYSION = {Name: "Elysion", Rate: 136}
export const ZONE_THE_SILDIHN_SUBTERRANE = {Name: "The Sil'dihn Subterrane", Rate: 0}
export const ZONE_ANOTHER_SILDIHN_SUBTERRANE = {Name: "Another Sil'dihn Subterrane", Rate: 0}
export const ZONE_THE_CAUSTIC_PURGATORY = {Name: "The Caustic Purgatory", Rate: 145}
export const ZONE_STYGIAN_INSENESCENCE_CELLS = {Name: "Stygian Insenescence Cells", Rate: 145}
export const ZONE_EUPHROSYNE = {Name: "Euphrosyne", Rate: 147}
export const ZONE_LAPIS_MANALIS = {Name: "Lapis Manalis", Rate: 42}
export const ZONE_THE_SHIFTING_GYMNASION_AGONON = {Name: "The Shifting Gymnasion Agonon", Rate: 0}
export const ZONE_SYLPHSTEP = {Name: "Sylphstep", Rate: 0}
export const ZONE_EUREKA_ORTHOS = {Name: "Eureka Orthos", Rate: 0}
export const ZONE_THE_CLOCKWORK_CASTLETOWN = {Name: "The Clockwork Castletown", Rate: 0}
export const ZONE_MOUNT_ORDEALS = {Name: "Mount Ordeals", Rate: 0}
export const ZONE_KHADGA = {Name: "Khadga", Rate: 0}
export const ZONE_THE_VOIDCAST_DAIS = {Name: "The Voidcast Dais", Rate: 149}
export const ZONE_THE_AETHERFONT = {Name: "The Aetherfont", Rate: 0}
export const ZONE_THE_DÆMONS_NEST = {Name: "The Dæmons' Nest", Rate: 145}
export const ZONE_ASCENSION = {Name: "Ascension", Rate: 145}
export const ZONE_APEX_OF_CREATION = {Name: "Apex of Creation", Rate: 145}
export const ZONE_THE_AETHERIAL_SLOUGH = {Name: "The Aetherial Slough", Rate: 0}
export const ZONE_THE_GILDED_ARAYA = {Name: "The Gilded Araya", Rate: 114}
export const ZONE_THE_CHAMBER_OF_FOURTEEN = {Name: "The Chamber of Fourteen", Rate: 145}
export const ZONE_ESTINIENS_CHAMBERS = {Name: "Estinien's Chambers", Rate: 138}
export const ZONE_SENATUS = {Name: "Senatus", Rate: 133}
export const ZONE_THE_RED_MOON = {Name: "The Red Moon", Rate: 149}
export const ZONE_MOUNT_ROKKON = {Name: "Mount Rokkon", Rate: 0}
export const ZONE_ANOTHER_MOUNT_ROKKON = {Name: "Another Mount Rokkon", Rate: 74}
export const ZONE_THE_RED_SANDS = {Name: "The Red Sands", Rate: 0}
export const ZONE_TULIYOLLAL = {Name: "Tuliyollal", Rate: 159}
export const ZONE_SOLUTION_NINE = {Name: "Solution Nine", Rate: 163}
export const ZONE_URQOPACHA = {Name: "Urqopacha", Rate: 160}
export const ZONE_KOZAMAUKA = {Name: "Kozama'uka", Rate: 161}
export const ZONE_YAK_TEL = {Name: "Yak T'el", Rate: 162}
export const ZONE_SHAALOANI = {Name: "Shaaloani", Rate: 164}
export const ZONE_HERITAGE_FOUND = {Name: "Heritage Found", Rate: 165}
export const ZONE_LIVING_MEMORY = {Name: "Living Memory", Rate: 166}
export const ZONE_THE_LUNAR_SUBTERRANE = {Name: "The Lunar Subterrane", Rate: 149}
export const ZONE_ALOALO_ISLAND = {Name: "Aloalo Island", Rate: 0}
export const ZONE_ANOTHER_ALOALO_ISLAND = {Name: "Another Aloalo Island", Rate: 0}
export const ZONE_BLUNDERVILLE = {Name: "Blunderville", Rate: 0}
export const ZONE_THALEIA = {Name: "Thaleia", Rate: 147}
export const ZONE_BLUNDERVILLE_SQUARE = {Name: "Blunderville Square", Rate: 0}
export const ZONE_THE_ABYSSAL_FRACTURE = {Name: "The Abyssal Fracture", Rate: 149}
export const ZONE_CENOTE_JA_JA_GURAL = {Name: "Cenote Ja Ja Gural", Rate: 0}
export const ZONE_IHUYKATUMU = {Name: "Ihuykatumu", Rate: 0}
export const ZONE_VANGUARD = {Name: "Vanguard", Rate: 0}
export const ZONE_TENDER_VALLEY = {Name: "Tender Valley", Rate: 0}
export const ZONE_WORQOR_ZORMOR = {Name: "Worqor Zormor", Rate: 0}
export const ZONE_ORIGENICS = {Name: "Origenics", Rate: 156}
export const ZONE_ALEXANDRIA = {Name: "Alexandria", Rate: 157}
export const ZONE_THE_SKYDEEP_CENOTE = {Name: "The Skydeep Cenote", Rate: 0}
export const ZONE_STRAYBOROUGH = {Name: "Strayborough", Rate: 150}
export const ZONE_LOVELY_LOVERING = {Name: "Lovely Lovering", Rate: 0}
export const ZONE_THE_THUNDERING = {Name: "The Thundering", Rate: 0}
export const ZONE_WORQOR_LAR_DOR = {Name: "Worqor Lar Dor", Rate: 0}
export const ZONE_BLASTING_RING = {Name: "Blasting Ring", Rate: 0}
export const ZONE_SCRATCHING_RING = {Name: "Scratching Ring", Rate: 0}
export const ZONE_INTERPHOS = {Name: "Interphos", Rate: 157}
export const ZONE_SUMMIT_OF_EVERKEEP = {Name: "Summit of Everkeep", Rate: 158}
export const ZONE_SUNPERCH = {Name: "Sunperch", Rate: 159}
export const ZONE_EARTHEN_SKY_HIDEOUT = {Name: "Earthen Sky Hideout", Rate: 165}
export const ZONE_MAIN_DECK = {Name: "Main Deck", Rate: 0}
export const ZONE_THE_BACKROOM = {Name: "The Backroom", Rate: 0}
export const ZONE_SKYDEEP_CENOTE_INNER_CHAMBER = {Name: "Skydeep Cenote Inner Chamber", Rate: 0}
export const ZONE_TRITAILS_TRAINING = {Name: "Tritails Training", Rate: 0}
export const ZONE_GREENROOM = {Name: "Greenroom", Rate: 0}
export const ZONE_THE_FORARD_CABINS = {Name: "The For'ard Cabins", Rate: 159}
export const ZONE_MANOR_BASEMENT = {Name: "Manor Basement", Rate: 0}
export const ZONE_DREAMLIKE_PALACE = {Name: "Dreamlike Palace", Rate: 0}
