export const Zones: {[key: string]: number} = {
  "Eorzea": 0,
  "New Gridania": 1,
  "Old Gridania": 2,
  "Central Shroud": 3,
  "East Shroud": 4,
  "South Shroud": 5,
  "North Shroud": 6,
  "The Tam-Tara Deepcroft": 0,
  "The Thousand Maws of Toto-Rak": 0,
  "Mordion Gaol": 0,
  "Limsa Lominsa Upper Decks": 14,
  "Limsa Lominsa Lower Decks": 15,
  "Ul'dah - Steps of Nald": 7,
  "Ul'dah - Steps of Thal": 8,
  "Middle La Noscea": 16,
  "Lower La Noscea": 17,
  "Eastern La Noscea": 18,
  "Western La Noscea": 19,
  "Upper La Noscea": 20,
  "Western Thanalan": 9,
  "Central Thanalan": 10,
  "Eastern Thanalan": 11,
  "Southern Thanalan": 12,
  "Northern Thanalan": 13,
  "Mor Dhona": 22,
  "Mizzenmast Inn": 0,
  "The Hourglass": 0,
  "The Roost": 0,
  "Outer La Noscea": 24,
  "Sastasha": 0,
  "The Wanderer's Palace": 0,
  "The Navel": 23,
  "Copperbell Mines": 0,
  "Bowl of Embers": 25,
  "Thornmarch": 30,
  "Stone Vigil": 27,
  "Aurum Vale": 0,
  "The Howling Eye": 26,
  "The Sunken Temple of Qarn": 0,
  "Brayflox's Longstop": 0,
  "Halatali": 0,
  "Castrum Meridianum": 0,
  "Haukke Manor": 0,
  "Amdapor Keep": 28,
  "Dzemael Darkhold": 0,
  "Wolves' Den Pier": 29,
  "Cutter's Cry": 0,
  "Coerthas Central Highlands": 21,
  "The Praetorium": 0,
  "Upper Aetheroacoustic Exploratory Site": 0,
  "Lower Aetheroacoustic Exploratory Site": 0,
  "Ragnarok Drive Cylinder": 0,
  "Ragnarok Central Core": 0,
  "Ragnarok Main Bridge": 0,
  "The Ragnarok": 0,
  "Central Decks": 0,
  "Seat of the First Bow": 0,
  "Lotus Stand": 0,
  "Labyrinth of the Ancients": 0,
  "Mist": 32,
  "Command Room": 14,
  "The Memory of Embers": 155,
  "A Future Rewritten": 0,
  "Heart of the Sworn": 0,
  "The Waking Sands": 0,
  "The Fold": 0,
  "The Lavender Beds": 34,
  "The Goblet": 33,
  "Eorzean Subterrane": 0,
  "Pharos Sirius": 28,
  "Private Cottage - Mist": 0,
  "Private House - Mist": 0,
  "Private Mansion - Mist": 0,
  "Private Cottage - The Lavender Beds": 0,
  "Private House - The Lavender Beds": 0,
  "Private Mansion - The Lavender Beds": 0,
  "Private Cottage - The Goblet": 0,
  "Private House - The Goblet": 0,
  "Private Mansion - The Goblet": 0,
  "The Rising Stones": 0,
  "Haukke Manor (Hard)": 0,
  "Copperbell Mines (Hard)": 0,
  "Porta Decumana": 31,
  "Griffin Crossing": 0,
  "Halatali (Hard)": 0,
  "Brayflox's Longstop (Hard)": 37,
  "The Whorleater": 38,
  "Dalamud's Shadow": 0,
  "The Outer Coil": 28,
  "The Holocharts": 0,
  "The Lost City of Amdapor": 40,
  "The Stone Vigil (Hard)": 42,
  "Syrcus Tower": 0,
  "The Tam-Tara Deepcroft (Hard)": 0,
  "The Striking Tree": 43,
  "Carteneau Flats: Borderland Ruins": 0,
  "Hullbreaker Isle": 0,
  "Sastasha (Hard)": 0,
  "Private Chambers - Mist": 0,
  "Private Chambers - The Lavender Beds": 0,
  "Private Chambers - The Goblet": 0,
  "Akh Afah Amphitheatre": 46,
  "Snowcloak": 42,
  "IC-06 Central Decks": 0,
  "IC-06 Regeneration Grid": 0,
  "IC-06 Main Bridge": 0,
  "The Burning Heart": 44,
  "Intercessory": 0,
  "The Sunken Temple of Qarn (Hard)": 41,
  "The World of Darkness": 0,
  "The Belly of the Beast": 0,
  "Steps of Faith": 28,
  "The Wanderer's Palace (Hard)": 40,
  "Amdapor Keep (Hard)": 40,
  "The Gold Saucer": 0,
  "Chocobo Square": 0,
  "The Keeper of the Lake": 74,
  "Company Workshop - Mist": 0,
  "Company Workshop - The Goblet": 0,
  "Company Workshop - The Lavender Beds": 0,
  "The Chrysalis": 0,
  "Sanctum of the Twelve": 4,
  "Coerthas Western Highlands": 49,
  "The Dravanian Forelands": 50,
  "The Dravanian Hinterlands": 51,
  "The Churning Mists": 52,
  "The Sea of Clouds": 53,
  "Azys Lla": 54,
  "Foundation": 47,
  "The Pillars": 48,
  "Saint Endalim's Scholasticate": 0,
  "Seat of the Lord Commander": 0,
  "Fortemps Manor": 0,
  "Cloud Nine": 0,
  "The Lightfeather Proving Grounds": 0,
  "Ruling Chamber": 0,
  "Sacrificial Chamber": 0,
  "Sohm Al Foothills": 0,
  "Neverreap": 0,
  "Aetherochemical Research Facility": 0,
  "The Limitless Blue": 28,
  "Singularity Reactor": 56,
  "The Fist of the Father": 0,
  "The Cuff of the Father": 0,
  "The Arm of the Father": 0,
  "The Burden of the Father": 0,
  "The Great Gubal Library": 0,
  "Seal Rock": 59,
  "Dusk Vigil": 42,
  "The Fractal Continuum": 0,
  "The Vault": 0,
  "The Aery": 28,
  "Matoya's Cave": 0,
  "Thok ast Thok": 57,
  "Idyllshire": 55,
  "The Gordian Knot": 0,
  "Central Azys Lla": 0,
  "Pharos Sirius (Hard)": 28,
  "The Eighteenth Floor": 0,
  "Saint Mocianne's Arboretum": 0,
  "Void Ark": 37,
  "The Antitower": 0,
  "The Lost City of Amdapor (Hard)": 63,
  "Containment Bay S1T7": 66,
  "The Feasting Grounds": 0,
  "The Fist of the Son": 0,
  "The Cuff of the Son": 0,
  "The Arm of the Son": 0,
  "The Burden of the Son": 0,
  "The Midan Knot": 0,
  "Sohr Khai": 0,
  "The Battlehall": 0,
  "The Fields of Glory": 67,
  "Hullbreaker Isle (Hard)": 68,
  "The Weeping City of Mhach": 0,
  "The Parrock": 0,
  "Leofard's Chambers": 0,
  "Twin Adder Barracks": 0,
  "Flame Barracks": 0,
  "Maelstrom Barracks": 0,
  "The Great Gubal Library (Hard)": 0,
  "Xelphatol": 40,
  "The Palace of the Dead": 0,
  "The Aquapolis": 0,
  "Last Remnant": 0,
  "Haunted Manor": 0,
  "Topmast Apartment Lobby": 0,
  "Lily Hills Apartment Lobby": 0,
  "Sultana's Breath Apartment Lobby": 0,
  "Topmast Apartment": 0,
  "Lily Hills Apartment": 0,
  "Sultana's Breath Apartment": 0,
  "Eyes of the Creator": 0,
  "Breath of the Creator": 0,
  "Heart of the Creator": 0,
  "Soul of the Creator": 0,
  "Containment Bay P1T6": 69,
  "Frondale's Home for Friendless Foundlings": 0,
  "Shisui of the Violet Tides": 0,
  "Baelsar's Wall": 40,
  "Dun Scaith": 58,
  "Lichenweed": 0,
  "Sohm Al (Hard)": 28,
  "Containment Bay Z1T9": 75,
  "Yanxia": 84,
  "Omega Control": 0,
  "The Diadem": 71,
  "The Sirensong Sea": 36,
  "Kugane Castle": 0,
  "The Temple of the Fist": 0,
  "Shirogane": 82,
  "Rhalgr's Reach": 78,
  "The Fringes": 79,
  "The Peaks": 80,
  "The Lochs": 81,
  "Kugane": 82,
  "The Ruby Sea": 83,
  "The Azim Steppe": 85,
  "Ala Mhigo": 0,
  "Bardam's Mettle": 0,
  "The Misery": 36,
  "Ruby Bazaar Offices": 0,
  "The House of the Fierce": 84,
  "The Doman Enclave": 84,
  "Bokairo Inn": 82,
  "The First Altar of Djanan Qhat": 0,
  "The Resonatorium": 0,
  "The Royal Menagerie": 0,
  "Kobai Goten Apartment Lobby": 0,
  "The Interdimensional Rift": 88,
  "Deltascape V1.0": 88,
  "Deltascape V2.0": 88,
  "Deltascape V3.0": 88,
  "Deltascape V4.0": 88,
  "Doma Castle": 0,
  "Castrum Abania": 0,
  "Emanation": 87,
  "The Blessed Treasury": 77,
  "The Royal Airship Landing": 76,
  "Transparency": 76,
  "The Lost Canals of Uznair": 0,
  "Astragalos": 0,
  "The Drowned City of Skalla": 0,
  "Eureka Anemos": 91,
  "The Binding Coil of Bahamut": 0,
  "The Hall of the Griffin": 0,
  "The Prima Vista Tiring Room": 0,
  "The Prima Vista Bridge": 0,
  "The Royal City of Rabanastre": 0,
  "Private Cottage - Shirogane": 0,
  "Private House - Shirogane": 0,
  "Private Mansion - Shirogane": 0,
  "Company Workshop - Shirogane": 0,
  "Private Chambers - Shirogane": 0,
  "Myth": 76,
  "Kobai Goten Apartment": 0,
  "Hells' Lid": 0,
  "Crystal Tower Training Grounds": 0,
  "The Fractal Continuum (Hard)": 0,
  "Sigmascape V1.0": 92,
  "Sigmascape V2.0": 92,
  "Sigmascape V3.0": 92,
  "Sigmascape V4.0": 92,
  "The Jade Stoa": 93,
  "Valentione's Ceremony": 0,
  "Kienkan": 0,
  "Reisen Temple": 0,
  "The Swallow's Compass": 0,
  "Eureka Pagos": 94,
  "The Great Hunt": 0,
  "Reisen Temple Road": 0,
  "The Ridorana Lighthouse": 0,
  "Ultimacy": 26,
  "Castrum Fluminis": 0,
  "Heaven-on-High": 0,
  "The Burn": 0,
  "Saint Mocianne's Arboretum (Hard)": 0,
  "The Ridorana Cataract": 0,
  "Eureka Pyros": 96,
  "Psiscape V1.0": 92,
  "Hidden Gorge": 0,
  "Kugane Ohashi": 0,
  "Blue Sky": 0,
  "Lakeland": 106,
  "Kholusia": 107,
  "Amh Araeng": 108,
  "Il Mheg": 109,
  "The Rak'tika Greatwood": 110,
  "The Tempest": 111,
  "The Crystarium": 112,
  "Eulmore": 113,
  "The Shifting Altars of Uznair": 0,
  "The Ghimlyt Dark": 0,
  "Psiscape V2.0": 92,
  "Hells' Kier": 98,
  "The Haunted Manor": 0,
  "The Fall of Belah'dia": 0,
  "The Qitana Ravel": 102,
  "The Orbonne Monastery": 0,
  "Eureka Hydatos": 100,
  "The Wreath of Snakes": 99,
  "Garlean Legion Tents": 0,
  "Eorzean Alliance Headquarters": 0,
  "Dohn Mheg": 0,
  "The Twinning": 0,
  "Amaurot": 105,
  "Mt. Gulg": 102,
  "Akadaemia Anyder": 0,
  "Malikah's Well": 102,
  "Holminster Switch": 102,
  "The Syrcus Trench": 0,
  "The Pendants Personal Suite": 112,
  "The Ocular": 0,
  "Dutiful Sisters of the Edelweiss": 15,
  "Dock Storehouse": 18,
  "The Nabaath Mines": 108,
  "Ronkan Reflections": 110,
  "The Crown of the Immaculate": 102,
  "The Confessional of Toupasa the Elder": 102,
  "The Dancing Plague": 103,
  "The Dying Gasp": 105,
  "The Core": 0,
  "The Halo": 0,
  "The Nereus Trench": 38,
  "Atlas Peak": 23,
  "The Dungeons of Lyhe Ghiah": 0,
  "The Empty": 0,
  "The Grand Cosmos": 0,
  "Onsal Hakair": 117,
  "The Copied Factory": 0,
  "Liminal Space": 0,
  "The Firmament": 47,
  "Excavation Tunnels": 0,
  "Lyhe Mheg": 40,
  "The Imperial Palace": 0,
  "Cinder Drift": 28,
  "Anamnesis Anyder": 0,
  "The Gandof Thunder Plains": 0,
  "Ashfall": 0,
  "The Heroes' Gauntlet": 125,
  "Trial's Threshold": 0,
  "Great Glacier": 46,
  "Cid's Memory": 123,
  "The Falling City of Nym": 0,
  "Frozen Reflections": 46,
  "Gangos": 0,
  "The Endeavor": 14,
  "Bozjan Southern Front": 124,
  "Transmission Control": 123,
  "The Puppets' Bunker": 0,
  "The Seat of Sacrifice": 125,
  "The Rift": 125,
  "Anogg's Lair": 0,
  "Castrum Lacus Litore": 124,
  "Terncliff": 0,
  "Terncliff Bay": 0,
  "Matoya's Relict": 0,
  "Sphere of Naught": 0,
  "The Garden of Nowhere": 0,
  "Laxan Loft": 0,
  "Castrum Marinum Drydocks": 0,
  "The Shifting Oubliettes of Lyhe Ghiah": 0,
  "Delubrum Reginae": 0,
  "The Last Trace": 0,
  "Bygone Gaol": 0,
  "The Tower at Paradigm's Breach": 0,
  "Zadnor": 130,
  "Paglth'an": 0,
  "G-Savior Deck": 0,
  "The Dalriada": 130,
  "The Dark Inside": 139,
  "The Mothercrystal": 139,
  "The Final Day": 116,
  "Empyreum": 142,
  "Ingleside Apartment Lobby": 0,
  "Private Cottage - Empyreum": 0,
  "Private House - Empyreum": 0,
  "Private Mansion - Empyreum": 0,
  "Company Workshop - Empyreum": 0,
  "Private Chambers - Empyreum": 0,
  "Ingleside Apartment": 0,
  "Old Sharlayan": 137,
  "Radz-at-Han": 138,
  "Labyrinthos": 131,
  "Thavnair": 132,
  "Garlemald": 133,
  "Mare Lamentorum": 135,
  "Ultima Thule": 136,
  "Elpis": 134,
  "The Tower of Zot": 0,
  "The Phantoms' Feast": 0,
  "Smileton": 0,
  "The Gates of Pandæmonium": 145,
  "Ktisis Hyperboreia": 0,
  "The Stigma Dreamscape": 140,
  "The Aitiascope": 0,
  "The Fervid Limbo": 145,
  "The Tower of Babil": 28,
  "The Excitatron 6000": 0,
  "The Stagnant Limbo": 145,
  "The Sanguine Limbo": 145,
  "The Dead Ends": 144,
  "Vanaspati": 141,
  "Lemures Headquarters": 0,
  "Main Hall": 137,
  "Andron": 137,
  "Strategy Room": 0,
  "Magna Glacies": 0,
  "Beyond the Stars": 143,
  "The Nethergate": 0,
  "Propylaion": 0,
  "Alzadaal's Legacy": 0,
  "Aglaia": 147,
  "Medias Res": 0,
  "The Palaistra": 0,
  "The Volcanic Heart": 0,
  "The Porta Decumana": 0,
  "The Omphalos": 147,
  "Restricted Archives": 137,
  "The Fell Court of Troia": 149,
  "The Pestilent Purgatory": 145,
  "Unnamed Island": 148,
  "Zero's Domain": 149,
  "Meghaduta Guest Chambers": 138,
  "Sneaky Hollow": 0,
  "Storm's Crown": 149,
  "The Hollow Purgatory": 145,
  "Elysion": 136,
  "The Sil'dihn Subterrane": 0,
  "Another Sil'dihn Subterrane": 0,
  "The Caustic Purgatory": 145,
  "Stygian Insenescence Cells": 145,
  "Euphrosyne": 147,
  "Lapis Manalis": 42,
  "The Shifting Gymnasion Agonon": 0,
  "Sylphstep": 0,
  "Eureka Orthos": 0,
  "The Clockwork Castletown": 0,
  "Mount Ordeals": 0,
  "Khadga": 0,
  "The Voidcast Dais": 149,
  "The Aetherfont": 0,
  "The Dæmons' Nest": 145,
  "Ascension": 145,
  "Apex of Creation": 145,
  "The Aetherial Slough": 0,
  "The Gilded Araya": 114,
  "The Chamber of Fourteen": 145,
  "Estinien's Chambers": 138,
  "Senatus": 133,
  "The Red Moon": 149,
  "Mount Rokkon": 0,
  "Another Mount Rokkon": 74,
  "The Red Sands": 0,
  "Tuliyollal": 159,
  "Solution Nine": 163,
  "Urqopacha": 160,
  "Kozama'uka": 161,
  "Yak T'el": 162,
  "Shaaloani": 164,
  "Heritage Found": 165,
  "Living Memory": 166,
  "The Lunar Subterrane": 149,
  "Aloalo Island": 0,
  "Another Aloalo Island": 0,
  "Blunderville": 0,
  "Thaleia": 147,
  "Blunderville Square": 0,
  "The Abyssal Fracture": 149,
  "Cenote Ja Ja Gural": 0,
  "Ihuykatumu": 0,
  "Vanguard": 0,
  "Tender Valley": 0,
  "Worqor Zormor": 0,
  "Origenics": 156,
  "Alexandria": 157,
  "The Skydeep Cenote": 0,
  "Strayborough": 150,
  "Lovely Lovering": 0,
  "The Thundering": 0,
  "Worqor Lar Dor": 0,
  "Blasting Ring": 0,
  "Scratching Ring": 0,
  "Interphos": 157,
  "Summit of Everkeep": 158,
  "Sunperch": 159,
  "Earthen Sky Hideout": 165,
  "Main Deck": 0,
  "The Backroom": 0,
  "Skydeep Cenote Inner Chamber": 0,
  "Tritails Training": 0,
  "Greenroom": 0,
  "The For'ard Cabins": 159,
  "Manor Basement": 0,
  "Dreamlike Palace": 0,
  "Yuweyawata": 86,
  "Jeuno: The First Walk": 150,
  "Lower Jeuno": 0,
  "Starlight Stalls": 27,
  "Hall of the Unbound": 0,
  "Norvrandt": 0,
  "Hydaelyn": 0,
  "Zorgor the Boundless": 0,
  "South Horn": 168,
  "Tower of Blood": 168,
  "Rebel Ring": 0,
  "Groovy Ring": 0,
  "Hunter's Ring": 0,
  "Hunting Ground": 0,
  "The Underkeep": 0,
  "Demolition Site": 0,
  "Sinus Ardorum": 169,
  "Break Room": 0,
  "Throne Room": 0,
  "Phantom Village": 0,
  "Recollection": 0,
  "San d'Oria: The Second Walk": 150,
  "The Ageless Necropolis": 0,
  "The Lightless Abyss": 0,
  "The Meso Terminal": 0,
  "Vault Oneiron": 0,
  "The Bayside Battleground": 0,
  "Containment Complex 10-29": 0,
  "Phaenna": 171
}