import { ZoneObject } from "../types/ZoneObject"
export const ZONE_EORZEA: ZoneObject = {Name: "Eorzea", Rate: 0}
export const ZONE_NEW_GRIDANIA: ZoneObject = {Name: "New Gridania", Rate: 1}
export const ZONE_OLD_GRIDANIA: ZoneObject = {Name: "Old Gridania", Rate: 2}
export const ZONE_CENTRAL_SHROUD: ZoneObject = {Name: "Central Shroud", Rate: 3}
export const ZONE_EAST_SHROUD: ZoneObject = {Name: "East Shroud", Rate: 4}
export const ZONE_SOUTH_SHROUD: ZoneObject = {Name: "South Shroud", Rate: 5}
export const ZONE_NORTH_SHROUD: ZoneObject = {Name: "North Shroud", Rate: 6}
export const ZONE_THE_TAMTARA_DEEPCROFT: ZoneObject = {Name: "The Tam-Tara Deepcroft", Rate: 0}
export const ZONE_THE_THOUSAND_MAWS_OF_TOTORAK: ZoneObject = {Name: "The Thousand Maws of Toto-Rak", Rate: 0}
export const ZONE_MORDION_GAOL: ZoneObject = {Name: "Mordion Gaol", Rate: 0}
export const ZONE_LIMSA_LOMINSA_UPPER_DECKS: ZoneObject = {Name: "Limsa Lominsa Upper Decks", Rate: 14}
export const ZONE_LIMSA_LOMINSA_LOWER_DECKS: ZoneObject = {Name: "Limsa Lominsa Lower Decks", Rate: 15}
export const ZONE_ULDAH__STEPS_OF_NALD: ZoneObject = {Name: "Ul'dah - Steps of Nald", Rate: 7}
export const ZONE_ULDAH__STEPS_OF_THAL: ZoneObject = {Name: "Ul'dah - Steps of Thal", Rate: 8}
export const ZONE_MIDDLE_LA_NOSCEA: ZoneObject = {Name: "Middle La Noscea", Rate: 16}
export const ZONE_LOWER_LA_NOSCEA: ZoneObject = {Name: "Lower La Noscea", Rate: 17}
export const ZONE_EASTERN_LA_NOSCEA: ZoneObject = {Name: "Eastern La Noscea", Rate: 18}
export const ZONE_WESTERN_LA_NOSCEA: ZoneObject = {Name: "Western La Noscea", Rate: 19}
export const ZONE_UPPER_LA_NOSCEA: ZoneObject = {Name: "Upper La Noscea", Rate: 20}
export const ZONE_WESTERN_THANALAN: ZoneObject = {Name: "Western Thanalan", Rate: 9}
export const ZONE_CENTRAL_THANALAN: ZoneObject = {Name: "Central Thanalan", Rate: 10}
export const ZONE_EASTERN_THANALAN: ZoneObject = {Name: "Eastern Thanalan", Rate: 11}
export const ZONE_SOUTHERN_THANALAN: ZoneObject = {Name: "Southern Thanalan", Rate: 12}
export const ZONE_NORTHERN_THANALAN: ZoneObject = {Name: "Northern Thanalan", Rate: 13}
export const ZONE_MOR_DHONA: ZoneObject = {Name: "Mor Dhona", Rate: 22}
export const ZONE_MIZZENMAST_INN: ZoneObject = {Name: "Mizzenmast Inn", Rate: 0}
export const ZONE_THE_HOURGLASS: ZoneObject = {Name: "The Hourglass", Rate: 0}
export const ZONE_THE_ROOST: ZoneObject = {Name: "The Roost", Rate: 0}
export const ZONE_OUTER_LA_NOSCEA: ZoneObject = {Name: "Outer La Noscea", Rate: 24}
export const ZONE_SASTASHA: ZoneObject = {Name: "Sastasha", Rate: 0}
export const ZONE_THE_WANDERERS_PALACE: ZoneObject = {Name: "The Wanderer's Palace", Rate: 0}
export const ZONE_THE_NAVEL: ZoneObject = {Name: "The Navel", Rate: 23}
export const ZONE_COPPERBELL_MINES: ZoneObject = {Name: "Copperbell Mines", Rate: 0}
export const ZONE_BOWL_OF_EMBERS: ZoneObject = {Name: "Bowl of Embers", Rate: 25}
export const ZONE_THORNMARCH: ZoneObject = {Name: "Thornmarch", Rate: 30}
export const ZONE_STONE_VIGIL: ZoneObject = {Name: "Stone Vigil", Rate: 27}
export const ZONE_AURUM_VALE: ZoneObject = {Name: "Aurum Vale", Rate: 0}
export const ZONE_THE_HOWLING_EYE: ZoneObject = {Name: "The Howling Eye", Rate: 26}
export const ZONE_THE_SUNKEN_TEMPLE_OF_QARN: ZoneObject = {Name: "The Sunken Temple of Qarn", Rate: 0}
export const ZONE_BRAYFLOXS_LONGSTOP: ZoneObject = {Name: "Brayflox's Longstop", Rate: 0}
export const ZONE_HALATALI: ZoneObject = {Name: "Halatali", Rate: 0}
export const ZONE_CASTRUM_MERIDIANUM: ZoneObject = {Name: "Castrum Meridianum", Rate: 0}
export const ZONE_HAUKKE_MANOR: ZoneObject = {Name: "Haukke Manor", Rate: 0}
export const ZONE_AMDAPOR_KEEP: ZoneObject = {Name: "Amdapor Keep", Rate: 28}
export const ZONE_DZEMAEL_DARKHOLD: ZoneObject = {Name: "Dzemael Darkhold", Rate: 0}
export const ZONE_WOLVES_DEN_PIER: ZoneObject = {Name: "Wolves' Den Pier", Rate: 29}
export const ZONE_CUTTERS_CRY: ZoneObject = {Name: "Cutter's Cry", Rate: 0}
export const ZONE_COERTHAS_CENTRAL_HIGHLANDS: ZoneObject = {Name: "Coerthas Central Highlands", Rate: 21}
export const ZONE_THE_PRAETORIUM: ZoneObject = {Name: "The Praetorium", Rate: 0}
export const ZONE_UPPER_AETHEROACOUSTIC_EXPLORATORY_SITE: ZoneObject = {Name: "Upper Aetheroacoustic Exploratory Site", Rate: 0}
export const ZONE_LOWER_AETHEROACOUSTIC_EXPLORATORY_SITE: ZoneObject = {Name: "Lower Aetheroacoustic Exploratory Site", Rate: 0}
export const ZONE_RAGNAROK_DRIVE_CYLINDER: ZoneObject = {Name: "Ragnarok Drive Cylinder", Rate: 0}
export const ZONE_RAGNAROK_CENTRAL_CORE: ZoneObject = {Name: "Ragnarok Central Core", Rate: 0}
export const ZONE_RAGNAROK_MAIN_BRIDGE: ZoneObject = {Name: "Ragnarok Main Bridge", Rate: 0}
export const ZONE_THE_RAGNAROK: ZoneObject = {Name: "The Ragnarok", Rate: 0}
export const ZONE_CENTRAL_DECKS: ZoneObject = {Name: "Central Decks", Rate: 0}
export const ZONE_SEAT_OF_THE_FIRST_BOW: ZoneObject = {Name: "Seat of the First Bow", Rate: 0}
export const ZONE_LOTUS_STAND: ZoneObject = {Name: "Lotus Stand", Rate: 0}
export const ZONE_LABYRINTH_OF_THE_ANCIENTS: ZoneObject = {Name: "Labyrinth of the Ancients", Rate: 0}
export const ZONE_MIST: ZoneObject = {Name: "Mist", Rate: 32}
export const ZONE_COMMAND_ROOM: ZoneObject = {Name: "Command Room", Rate: 14}
export const ZONE_THE_MEMORY_OF_EMBERS: ZoneObject = {Name: "The Memory of Embers", Rate: 155}
export const ZONE_A_FUTURE_REWRITTEN: ZoneObject = {Name: "A Future Rewritten", Rate: 0}
export const ZONE_HEART_OF_THE_SWORN: ZoneObject = {Name: "Heart of the Sworn", Rate: 0}
export const ZONE_THE_WAKING_SANDS: ZoneObject = {Name: "The Waking Sands", Rate: 0}
export const ZONE_THE_FOLD: ZoneObject = {Name: "The Fold", Rate: 0}
export const ZONE_THE_LAVENDER_BEDS: ZoneObject = {Name: "The Lavender Beds", Rate: 34}
export const ZONE_THE_GOBLET: ZoneObject = {Name: "The Goblet", Rate: 33}
export const ZONE_EORZEAN_SUBTERRANE: ZoneObject = {Name: "Eorzean Subterrane", Rate: 0}
export const ZONE_PHAROS_SIRIUS: ZoneObject = {Name: "Pharos Sirius", Rate: 28}
export const ZONE_PRIVATE_COTTAGE__MIST: ZoneObject = {Name: "Private Cottage - Mist", Rate: 0}
export const ZONE_PRIVATE_HOUSE__MIST: ZoneObject = {Name: "Private House - Mist", Rate: 0}
export const ZONE_PRIVATE_MANSION__MIST: ZoneObject = {Name: "Private Mansion - Mist", Rate: 0}
export const ZONE_PRIVATE_COTTAGE__THE_LAVENDER_BEDS: ZoneObject = {Name: "Private Cottage - The Lavender Beds", Rate: 0}
export const ZONE_PRIVATE_HOUSE__THE_LAVENDER_BEDS: ZoneObject = {Name: "Private House - The Lavender Beds", Rate: 0}
export const ZONE_PRIVATE_MANSION__THE_LAVENDER_BEDS: ZoneObject = {Name: "Private Mansion - The Lavender Beds", Rate: 0}
export const ZONE_PRIVATE_COTTAGE__THE_GOBLET: ZoneObject = {Name: "Private Cottage - The Goblet", Rate: 0}
export const ZONE_PRIVATE_HOUSE__THE_GOBLET: ZoneObject = {Name: "Private House - The Goblet", Rate: 0}
export const ZONE_PRIVATE_MANSION__THE_GOBLET: ZoneObject = {Name: "Private Mansion - The Goblet", Rate: 0}
export const ZONE_THE_RISING_STONES: ZoneObject = {Name: "The Rising Stones", Rate: 0}
export const ZONE_HAUKKE_MANOR_HARD: ZoneObject = {Name: "Haukke Manor (Hard)", Rate: 0}
export const ZONE_COPPERBELL_MINES_HARD: ZoneObject = {Name: "Copperbell Mines (Hard)", Rate: 0}
export const ZONE_PORTA_DECUMANA: ZoneObject = {Name: "Porta Decumana", Rate: 31}
export const ZONE_GRIFFIN_CROSSING: ZoneObject = {Name: "Griffin Crossing", Rate: 0}
export const ZONE_HALATALI_HARD: ZoneObject = {Name: "Halatali (Hard)", Rate: 0}
export const ZONE_BRAYFLOXS_LONGSTOP_HARD: ZoneObject = {Name: "Brayflox's Longstop (Hard)", Rate: 37}
export const ZONE_THE_WHORLEATER: ZoneObject = {Name: "The Whorleater", Rate: 38}
export const ZONE_DALAMUDS_SHADOW: ZoneObject = {Name: "Dalamud's Shadow", Rate: 0}
export const ZONE_THE_OUTER_COIL: ZoneObject = {Name: "The Outer Coil", Rate: 28}
export const ZONE_THE_HOLOCHARTS: ZoneObject = {Name: "The Holocharts", Rate: 0}
export const ZONE_THE_LOST_CITY_OF_AMDAPOR: ZoneObject = {Name: "The Lost City of Amdapor", Rate: 40}
export const ZONE_THE_STONE_VIGIL_HARD: ZoneObject = {Name: "The Stone Vigil (Hard)", Rate: 42}
export const ZONE_SYRCUS_TOWER: ZoneObject = {Name: "Syrcus Tower", Rate: 0}
export const ZONE_THE_TAMTARA_DEEPCROFT_HARD: ZoneObject = {Name: "The Tam-Tara Deepcroft (Hard)", Rate: 0}
export const ZONE_THE_STRIKING_TREE: ZoneObject = {Name: "The Striking Tree", Rate: 43}
export const ZONE_CARTENEAU_FLATS_BORDERLAND_RUINS: ZoneObject = {Name: "Carteneau Flats: Borderland Ruins", Rate: 0}
export const ZONE_HULLBREAKER_ISLE: ZoneObject = {Name: "Hullbreaker Isle", Rate: 0}
export const ZONE_SASTASHA_HARD: ZoneObject = {Name: "Sastasha (Hard)", Rate: 0}
export const ZONE_PRIVATE_CHAMBERS__MIST: ZoneObject = {Name: "Private Chambers - Mist", Rate: 0}
export const ZONE_PRIVATE_CHAMBERS__THE_LAVENDER_BEDS: ZoneObject = {Name: "Private Chambers - The Lavender Beds", Rate: 0}
export const ZONE_PRIVATE_CHAMBERS__THE_GOBLET: ZoneObject = {Name: "Private Chambers - The Goblet", Rate: 0}
export const ZONE_AKH_AFAH_AMPHITHEATRE: ZoneObject = {Name: "Akh Afah Amphitheatre", Rate: 46}
export const ZONE_SNOWCLOAK: ZoneObject = {Name: "Snowcloak", Rate: 42}
export const ZONE_IC06_CENTRAL_DECKS: ZoneObject = {Name: "IC-06 Central Decks", Rate: 0}
export const ZONE_IC06_REGENERATION_GRID: ZoneObject = {Name: "IC-06 Regeneration Grid", Rate: 0}
export const ZONE_IC06_MAIN_BRIDGE: ZoneObject = {Name: "IC-06 Main Bridge", Rate: 0}
export const ZONE_THE_BURNING_HEART: ZoneObject = {Name: "The Burning Heart", Rate: 44}
export const ZONE_INTERCESSORY: ZoneObject = {Name: "Intercessory", Rate: 0}
export const ZONE_THE_SUNKEN_TEMPLE_OF_QARN_HARD: ZoneObject = {Name: "The Sunken Temple of Qarn (Hard)", Rate: 41}
export const ZONE_THE_WORLD_OF_DARKNESS: ZoneObject = {Name: "The World of Darkness", Rate: 0}
export const ZONE_THE_BELLY_OF_THE_BEAST: ZoneObject = {Name: "The Belly of the Beast", Rate: 0}
export const ZONE_STEPS_OF_FAITH: ZoneObject = {Name: "Steps of Faith", Rate: 28}
export const ZONE_THE_WANDERERS_PALACE_HARD: ZoneObject = {Name: "The Wanderer's Palace (Hard)", Rate: 40}
export const ZONE_AMDAPOR_KEEP_HARD: ZoneObject = {Name: "Amdapor Keep (Hard)", Rate: 40}
export const ZONE_THE_GOLD_SAUCER: ZoneObject = {Name: "The Gold Saucer", Rate: 0}
export const ZONE_CHOCOBO_SQUARE: ZoneObject = {Name: "Chocobo Square", Rate: 0}
export const ZONE_THE_KEEPER_OF_THE_LAKE: ZoneObject = {Name: "The Keeper of the Lake", Rate: 74}
export const ZONE_COMPANY_WORKSHOP__MIST: ZoneObject = {Name: "Company Workshop - Mist", Rate: 0}
export const ZONE_COMPANY_WORKSHOP__THE_GOBLET: ZoneObject = {Name: "Company Workshop - The Goblet", Rate: 0}
export const ZONE_COMPANY_WORKSHOP__THE_LAVENDER_BEDS: ZoneObject = {Name: "Company Workshop - The Lavender Beds", Rate: 0}
export const ZONE_THE_CHRYSALIS: ZoneObject = {Name: "The Chrysalis", Rate: 0}
export const ZONE_SANCTUM_OF_THE_TWELVE: ZoneObject = {Name: "Sanctum of the Twelve", Rate: 4}
export const ZONE_COERTHAS_WESTERN_HIGHLANDS: ZoneObject = {Name: "Coerthas Western Highlands", Rate: 49}
export const ZONE_THE_DRAVANIAN_FORELANDS: ZoneObject = {Name: "The Dravanian Forelands", Rate: 50}
export const ZONE_THE_DRAVANIAN_HINTERLANDS: ZoneObject = {Name: "The Dravanian Hinterlands", Rate: 51}
export const ZONE_THE_CHURNING_MISTS: ZoneObject = {Name: "The Churning Mists", Rate: 52}
export const ZONE_THE_SEA_OF_CLOUDS: ZoneObject = {Name: "The Sea of Clouds", Rate: 53}
export const ZONE_AZYS_LLA: ZoneObject = {Name: "Azys Lla", Rate: 54}
export const ZONE_FOUNDATION: ZoneObject = {Name: "Foundation", Rate: 47}
export const ZONE_THE_PILLARS: ZoneObject = {Name: "The Pillars", Rate: 48}
export const ZONE_SAINT_ENDALIMS_SCHOLASTICATE: ZoneObject = {Name: "Saint Endalim's Scholasticate", Rate: 0}
export const ZONE_SEAT_OF_THE_LORD_COMMANDER: ZoneObject = {Name: "Seat of the Lord Commander", Rate: 0}
export const ZONE_FORTEMPS_MANOR: ZoneObject = {Name: "Fortemps Manor", Rate: 0}
export const ZONE_CLOUD_NINE: ZoneObject = {Name: "Cloud Nine", Rate: 0}
export const ZONE_THE_LIGHTFEATHER_PROVING_GROUNDS: ZoneObject = {Name: "The Lightfeather Proving Grounds", Rate: 0}
export const ZONE_RULING_CHAMBER: ZoneObject = {Name: "Ruling Chamber", Rate: 0}
export const ZONE_SACRIFICIAL_CHAMBER: ZoneObject = {Name: "Sacrificial Chamber", Rate: 0}
export const ZONE_SOHM_AL_FOOTHILLS: ZoneObject = {Name: "Sohm Al Foothills", Rate: 0}
export const ZONE_NEVERREAP: ZoneObject = {Name: "Neverreap", Rate: 0}
export const ZONE_AETHEROCHEMICAL_RESEARCH_FACILITY: ZoneObject = {Name: "Aetherochemical Research Facility", Rate: 0}
export const ZONE_THE_LIMITLESS_BLUE: ZoneObject = {Name: "The Limitless Blue", Rate: 28}
export const ZONE_SINGULARITY_REACTOR: ZoneObject = {Name: "Singularity Reactor", Rate: 56}
export const ZONE_THE_FIST_OF_THE_FATHER: ZoneObject = {Name: "The Fist of the Father", Rate: 0}
export const ZONE_THE_CUFF_OF_THE_FATHER: ZoneObject = {Name: "The Cuff of the Father", Rate: 0}
export const ZONE_THE_ARM_OF_THE_FATHER: ZoneObject = {Name: "The Arm of the Father", Rate: 0}
export const ZONE_THE_BURDEN_OF_THE_FATHER: ZoneObject = {Name: "The Burden of the Father", Rate: 0}
export const ZONE_THE_GREAT_GUBAL_LIBRARY: ZoneObject = {Name: "The Great Gubal Library", Rate: 0}
export const ZONE_SEAL_ROCK: ZoneObject = {Name: "Seal Rock", Rate: 59}
export const ZONE_DUSK_VIGIL: ZoneObject = {Name: "Dusk Vigil", Rate: 42}
export const ZONE_THE_FRACTAL_CONTINUUM: ZoneObject = {Name: "The Fractal Continuum", Rate: 0}
export const ZONE_THE_VAULT: ZoneObject = {Name: "The Vault", Rate: 0}
export const ZONE_THE_AERY: ZoneObject = {Name: "The Aery", Rate: 28}
export const ZONE_MATOYAS_CAVE: ZoneObject = {Name: "Matoya's Cave", Rate: 0}
export const ZONE_THOK_AST_THOK: ZoneObject = {Name: "Thok ast Thok", Rate: 57}
export const ZONE_IDYLLSHIRE: ZoneObject = {Name: "Idyllshire", Rate: 55}
export const ZONE_THE_GORDIAN_KNOT: ZoneObject = {Name: "The Gordian Knot", Rate: 0}
export const ZONE_CENTRAL_AZYS_LLA: ZoneObject = {Name: "Central Azys Lla", Rate: 0}
export const ZONE_PHAROS_SIRIUS_HARD: ZoneObject = {Name: "Pharos Sirius (Hard)", Rate: 28}
export const ZONE_THE_EIGHTEENTH_FLOOR: ZoneObject = {Name: "The Eighteenth Floor", Rate: 0}
export const ZONE_SAINT_MOCIANNES_ARBORETUM: ZoneObject = {Name: "Saint Mocianne's Arboretum", Rate: 0}
export const ZONE_VOID_ARK: ZoneObject = {Name: "Void Ark", Rate: 37}
export const ZONE_THE_ANTITOWER: ZoneObject = {Name: "The Antitower", Rate: 0}
export const ZONE_THE_LOST_CITY_OF_AMDAPOR_HARD: ZoneObject = {Name: "The Lost City of Amdapor (Hard)", Rate: 63}
export const ZONE_CONTAINMENT_BAY_S1T7: ZoneObject = {Name: "Containment Bay S1T7", Rate: 66}
export const ZONE_THE_FEASTING_GROUNDS: ZoneObject = {Name: "The Feasting Grounds", Rate: 0}
export const ZONE_THE_FIST_OF_THE_SON: ZoneObject = {Name: "The Fist of the Son", Rate: 0}
export const ZONE_THE_CUFF_OF_THE_SON: ZoneObject = {Name: "The Cuff of the Son", Rate: 0}
export const ZONE_THE_ARM_OF_THE_SON: ZoneObject = {Name: "The Arm of the Son", Rate: 0}
export const ZONE_THE_BURDEN_OF_THE_SON: ZoneObject = {Name: "The Burden of the Son", Rate: 0}
export const ZONE_THE_MIDAN_KNOT: ZoneObject = {Name: "The Midan Knot", Rate: 0}
export const ZONE_SOHR_KHAI: ZoneObject = {Name: "Sohr Khai", Rate: 0}
export const ZONE_THE_BATTLEHALL: ZoneObject = {Name: "The Battlehall", Rate: 0}
export const ZONE_THE_FIELDS_OF_GLORY: ZoneObject = {Name: "The Fields of Glory", Rate: 67}
export const ZONE_HULLBREAKER_ISLE_HARD: ZoneObject = {Name: "Hullbreaker Isle (Hard)", Rate: 68}
export const ZONE_THE_WEEPING_CITY_OF_MHACH: ZoneObject = {Name: "The Weeping City of Mhach", Rate: 0}
export const ZONE_THE_PARROCK: ZoneObject = {Name: "The Parrock", Rate: 0}
export const ZONE_LEOFARDS_CHAMBERS: ZoneObject = {Name: "Leofard's Chambers", Rate: 0}
export const ZONE_TWIN_ADDER_BARRACKS: ZoneObject = {Name: "Twin Adder Barracks", Rate: 0}
export const ZONE_FLAME_BARRACKS: ZoneObject = {Name: "Flame Barracks", Rate: 0}
export const ZONE_MAELSTROM_BARRACKS: ZoneObject = {Name: "Maelstrom Barracks", Rate: 0}
export const ZONE_THE_GREAT_GUBAL_LIBRARY_HARD: ZoneObject = {Name: "The Great Gubal Library (Hard)", Rate: 0}
export const ZONE_XELPHATOL: ZoneObject = {Name: "Xelphatol", Rate: 40}
export const ZONE_THE_PALACE_OF_THE_DEAD: ZoneObject = {Name: "The Palace of the Dead", Rate: 0}
export const ZONE_THE_AQUAPOLIS: ZoneObject = {Name: "The Aquapolis", Rate: 0}
export const ZONE_LAST_REMNANT: ZoneObject = {Name: "Last Remnant", Rate: 0}
export const ZONE_HAUNTED_MANOR: ZoneObject = {Name: "Haunted Manor", Rate: 0}
export const ZONE_TOPMAST_APARTMENT_LOBBY: ZoneObject = {Name: "Topmast Apartment Lobby", Rate: 0}
export const ZONE_LILY_HILLS_APARTMENT_LOBBY: ZoneObject = {Name: "Lily Hills Apartment Lobby", Rate: 0}
export const ZONE_SULTANAS_BREATH_APARTMENT_LOBBY: ZoneObject = {Name: "Sultana's Breath Apartment Lobby", Rate: 0}
export const ZONE_TOPMAST_APARTMENT: ZoneObject = {Name: "Topmast Apartment", Rate: 0}
export const ZONE_LILY_HILLS_APARTMENT: ZoneObject = {Name: "Lily Hills Apartment", Rate: 0}
export const ZONE_SULTANAS_BREATH_APARTMENT: ZoneObject = {Name: "Sultana's Breath Apartment", Rate: 0}
export const ZONE_EYES_OF_THE_CREATOR: ZoneObject = {Name: "Eyes of the Creator", Rate: 0}
export const ZONE_BREATH_OF_THE_CREATOR: ZoneObject = {Name: "Breath of the Creator", Rate: 0}
export const ZONE_HEART_OF_THE_CREATOR: ZoneObject = {Name: "Heart of the Creator", Rate: 0}
export const ZONE_SOUL_OF_THE_CREATOR: ZoneObject = {Name: "Soul of the Creator", Rate: 0}
export const ZONE_CONTAINMENT_BAY_P1T6: ZoneObject = {Name: "Containment Bay P1T6", Rate: 69}
export const ZONE_FRONDALES_HOME_FOR_FRIENDLESS_FOUNDLINGS: ZoneObject = {Name: "Frondale's Home for Friendless Foundlings", Rate: 0}
export const ZONE_SHISUI_OF_THE_VIOLET_TIDES: ZoneObject = {Name: "Shisui of the Violet Tides", Rate: 0}
export const ZONE_BAELSARS_WALL: ZoneObject = {Name: "Baelsar's Wall", Rate: 40}
export const ZONE_DUN_SCAITH: ZoneObject = {Name: "Dun Scaith", Rate: 58}
export const ZONE_LICHENWEED: ZoneObject = {Name: "Lichenweed", Rate: 0}
export const ZONE_SOHM_AL_HARD: ZoneObject = {Name: "Sohm Al (Hard)", Rate: 28}
export const ZONE_CONTAINMENT_BAY_Z1T9: ZoneObject = {Name: "Containment Bay Z1T9", Rate: 75}
export const ZONE_YANXIA: ZoneObject = {Name: "Yanxia", Rate: 84}
export const ZONE_OMEGA_CONTROL: ZoneObject = {Name: "Omega Control", Rate: 0}
export const ZONE_THE_DIADEM: ZoneObject = {Name: "The Diadem", Rate: 71}
export const ZONE_THE_SIRENSONG_SEA: ZoneObject = {Name: "The Sirensong Sea", Rate: 36}
export const ZONE_KUGANE_CASTLE: ZoneObject = {Name: "Kugane Castle", Rate: 0}
export const ZONE_THE_TEMPLE_OF_THE_FIST: ZoneObject = {Name: "The Temple of the Fist", Rate: 0}
export const ZONE_SHIROGANE: ZoneObject = {Name: "Shirogane", Rate: 82}
export const ZONE_RHALGRS_REACH: ZoneObject = {Name: "Rhalgr's Reach", Rate: 78}
export const ZONE_THE_FRINGES: ZoneObject = {Name: "The Fringes", Rate: 79}
export const ZONE_THE_PEAKS: ZoneObject = {Name: "The Peaks", Rate: 80}
export const ZONE_THE_LOCHS: ZoneObject = {Name: "The Lochs", Rate: 81}
export const ZONE_KUGANE: ZoneObject = {Name: "Kugane", Rate: 82}
export const ZONE_THE_RUBY_SEA: ZoneObject = {Name: "The Ruby Sea", Rate: 83}
export const ZONE_THE_AZIM_STEPPE: ZoneObject = {Name: "The Azim Steppe", Rate: 85}
export const ZONE_ALA_MHIGO: ZoneObject = {Name: "Ala Mhigo", Rate: 0}
export const ZONE_BARDAMS_METTLE: ZoneObject = {Name: "Bardam's Mettle", Rate: 0}
export const ZONE_THE_MISERY: ZoneObject = {Name: "The Misery", Rate: 36}
export const ZONE_RUBY_BAZAAR_OFFICES: ZoneObject = {Name: "Ruby Bazaar Offices", Rate: 0}
export const ZONE_THE_HOUSE_OF_THE_FIERCE: ZoneObject = {Name: "The House of the Fierce", Rate: 84}
export const ZONE_THE_DOMAN_ENCLAVE: ZoneObject = {Name: "The Doman Enclave", Rate: 84}
export const ZONE_BOKAIRO_INN: ZoneObject = {Name: "Bokairo Inn", Rate: 82}
export const ZONE_THE_FIRST_ALTAR_OF_DJANAN_QHAT: ZoneObject = {Name: "The First Altar of Djanan Qhat", Rate: 0}
export const ZONE_THE_RESONATORIUM: ZoneObject = {Name: "The Resonatorium", Rate: 0}
export const ZONE_THE_ROYAL_MENAGERIE: ZoneObject = {Name: "The Royal Menagerie", Rate: 0}
export const ZONE_KOBAI_GOTEN_APARTMENT_LOBBY: ZoneObject = {Name: "Kobai Goten Apartment Lobby", Rate: 0}
export const ZONE_THE_INTERDIMENSIONAL_RIFT: ZoneObject = {Name: "The Interdimensional Rift", Rate: 88}
export const ZONE_DELTASCAPE_V1: ZoneObject = {Name: "Deltascape V1.0", Rate: 88}
export const ZONE_DELTASCAPE_V2: ZoneObject = {Name: "Deltascape V2.0", Rate: 88}
export const ZONE_DELTASCAPE_V3: ZoneObject = {Name: "Deltascape V3.0", Rate: 88}
export const ZONE_DELTASCAPE_V4: ZoneObject = {Name: "Deltascape V4.0", Rate: 88}
export const ZONE_DOMA_CASTLE: ZoneObject = {Name: "Doma Castle", Rate: 0}
export const ZONE_CASTRUM_ABANIA: ZoneObject = {Name: "Castrum Abania", Rate: 0}
export const ZONE_EMANATION: ZoneObject = {Name: "Emanation", Rate: 87}
export const ZONE_THE_BLESSED_TREASURY: ZoneObject = {Name: "The Blessed Treasury", Rate: 77}
export const ZONE_THE_ROYAL_AIRSHIP_LANDING: ZoneObject = {Name: "The Royal Airship Landing", Rate: 76}
export const ZONE_TRANSPARENCY: ZoneObject = {Name: "Transparency", Rate: 76}
export const ZONE_THE_LOST_CANALS_OF_UZNAIR: ZoneObject = {Name: "The Lost Canals of Uznair", Rate: 0}
export const ZONE_ASTRAGALOS: ZoneObject = {Name: "Astragalos", Rate: 0}
export const ZONE_THE_DROWNED_CITY_OF_SKALLA: ZoneObject = {Name: "The Drowned City of Skalla", Rate: 0}
export const ZONE_EUREKA_ANEMOS: ZoneObject = {Name: "Eureka Anemos", Rate: 91}
export const ZONE_THE_BINDING_COIL_OF_BAHAMUT: ZoneObject = {Name: "The Binding Coil of Bahamut", Rate: 0}
export const ZONE_THE_HALL_OF_THE_GRIFFIN: ZoneObject = {Name: "The Hall of the Griffin", Rate: 0}
export const ZONE_THE_PRIMA_VISTA_TIRING_ROOM: ZoneObject = {Name: "The Prima Vista Tiring Room", Rate: 0}
export const ZONE_THE_PRIMA_VISTA_BRIDGE: ZoneObject = {Name: "The Prima Vista Bridge", Rate: 0}
export const ZONE_THE_ROYAL_CITY_OF_RABANASTRE: ZoneObject = {Name: "The Royal City of Rabanastre", Rate: 0}
export const ZONE_PRIVATE_COTTAGE__SHIROGANE: ZoneObject = {Name: "Private Cottage - Shirogane", Rate: 0}
export const ZONE_PRIVATE_HOUSE__SHIROGANE: ZoneObject = {Name: "Private House - Shirogane", Rate: 0}
export const ZONE_PRIVATE_MANSION__SHIROGANE: ZoneObject = {Name: "Private Mansion - Shirogane", Rate: 0}
export const ZONE_COMPANY_WORKSHOP__SHIROGANE: ZoneObject = {Name: "Company Workshop - Shirogane", Rate: 0}
export const ZONE_PRIVATE_CHAMBERS__SHIROGANE: ZoneObject = {Name: "Private Chambers - Shirogane", Rate: 0}
export const ZONE_MYTH: ZoneObject = {Name: "Myth", Rate: 76}
export const ZONE_KOBAI_GOTEN_APARTMENT: ZoneObject = {Name: "Kobai Goten Apartment", Rate: 0}
export const ZONE_HELLS_LID: ZoneObject = {Name: "Hells' Lid", Rate: 0}
export const ZONE_CRYSTAL_TOWER_TRAINING_GROUNDS: ZoneObject = {Name: "Crystal Tower Training Grounds", Rate: 0}
export const ZONE_THE_FRACTAL_CONTINUUM_HARD: ZoneObject = {Name: "The Fractal Continuum (Hard)", Rate: 0}
export const ZONE_SIGMASCAPE_V1: ZoneObject = {Name: "Sigmascape V1.0", Rate: 92}
export const ZONE_SIGMASCAPE_V2: ZoneObject = {Name: "Sigmascape V2.0", Rate: 92}
export const ZONE_SIGMASCAPE_V3: ZoneObject = {Name: "Sigmascape V3.0", Rate: 92}
export const ZONE_SIGMASCAPE_V4: ZoneObject = {Name: "Sigmascape V4.0", Rate: 92}
export const ZONE_THE_JADE_STOA: ZoneObject = {Name: "The Jade Stoa", Rate: 93}
export const ZONE_VALENTIONES_CEREMONY: ZoneObject = {Name: "Valentione's Ceremony", Rate: 0}
export const ZONE_KIENKAN: ZoneObject = {Name: "Kienkan", Rate: 0}
export const ZONE_REISEN_TEMPLE: ZoneObject = {Name: "Reisen Temple", Rate: 0}
export const ZONE_THE_SWALLOWS_COMPASS: ZoneObject = {Name: "The Swallow's Compass", Rate: 0}
export const ZONE_EUREKA_PAGOS: ZoneObject = {Name: "Eureka Pagos", Rate: 94}
export const ZONE_THE_GREAT_HUNT: ZoneObject = {Name: "The Great Hunt", Rate: 0}
export const ZONE_REISEN_TEMPLE_ROAD: ZoneObject = {Name: "Reisen Temple Road", Rate: 0}
export const ZONE_THE_RIDORANA_LIGHTHOUSE: ZoneObject = {Name: "The Ridorana Lighthouse", Rate: 0}
export const ZONE_ULTIMACY: ZoneObject = {Name: "Ultimacy", Rate: 26}
export const ZONE_CASTRUM_FLUMINIS: ZoneObject = {Name: "Castrum Fluminis", Rate: 0}
export const ZONE_HEAVENONHIGH: ZoneObject = {Name: "Heaven-on-High", Rate: 0}
export const ZONE_THE_BURN: ZoneObject = {Name: "The Burn", Rate: 0}
export const ZONE_SAINT_MOCIANNES_ARBORETUM_HARD: ZoneObject = {Name: "Saint Mocianne's Arboretum (Hard)", Rate: 0}
export const ZONE_THE_RIDORANA_CATARACT: ZoneObject = {Name: "The Ridorana Cataract", Rate: 0}
export const ZONE_EUREKA_PYROS: ZoneObject = {Name: "Eureka Pyros", Rate: 96}
export const ZONE_PSISCAPE_V1: ZoneObject = {Name: "Psiscape V1.0", Rate: 92}
export const ZONE_HIDDEN_GORGE: ZoneObject = {Name: "Hidden Gorge", Rate: 0}
export const ZONE_KUGANE_OHASHI: ZoneObject = {Name: "Kugane Ohashi", Rate: 0}
export const ZONE_BLUE_SKY: ZoneObject = {Name: "Blue Sky", Rate: 0}
export const ZONE_LAKELAND: ZoneObject = {Name: "Lakeland", Rate: 106}
export const ZONE_KHOLUSIA: ZoneObject = {Name: "Kholusia", Rate: 107}
export const ZONE_AMH_ARAENG: ZoneObject = {Name: "Amh Araeng", Rate: 108}
export const ZONE_IL_MHEG: ZoneObject = {Name: "Il Mheg", Rate: 109}
export const ZONE_THE_RAKTIKA_GREATWOOD: ZoneObject = {Name: "The Rak'tika Greatwood", Rate: 110}
export const ZONE_THE_TEMPEST: ZoneObject = {Name: "The Tempest", Rate: 111}
export const ZONE_THE_CRYSTARIUM: ZoneObject = {Name: "The Crystarium", Rate: 112}
export const ZONE_EULMORE: ZoneObject = {Name: "Eulmore", Rate: 113}
export const ZONE_THE_SHIFTING_ALTARS_OF_UZNAIR: ZoneObject = {Name: "The Shifting Altars of Uznair", Rate: 0}
export const ZONE_THE_GHIMLYT_DARK: ZoneObject = {Name: "The Ghimlyt Dark", Rate: 0}
export const ZONE_PSISCAPE_V2: ZoneObject = {Name: "Psiscape V2.0", Rate: 92}
export const ZONE_HELLS_KIER: ZoneObject = {Name: "Hells' Kier", Rate: 98}
export const ZONE_THE_HAUNTED_MANOR: ZoneObject = {Name: "The Haunted Manor", Rate: 0}
export const ZONE_THE_FALL_OF_BELAHDIA: ZoneObject = {Name: "The Fall of Belah'dia", Rate: 0}
export const ZONE_THE_QITANA_RAVEL: ZoneObject = {Name: "The Qitana Ravel", Rate: 102}
export const ZONE_THE_ORBONNE_MONASTERY: ZoneObject = {Name: "The Orbonne Monastery", Rate: 0}
export const ZONE_EUREKA_HYDATOS: ZoneObject = {Name: "Eureka Hydatos", Rate: 100}
export const ZONE_THE_WREATH_OF_SNAKES: ZoneObject = {Name: "The Wreath of Snakes", Rate: 99}
export const ZONE_GARLEAN_LEGION_TENTS: ZoneObject = {Name: "Garlean Legion Tents", Rate: 0}
export const ZONE_EORZEAN_ALLIANCE_HEADQUARTERS: ZoneObject = {Name: "Eorzean Alliance Headquarters", Rate: 0}
export const ZONE_DOHN_MHEG: ZoneObject = {Name: "Dohn Mheg", Rate: 0}
export const ZONE_THE_TWINNING: ZoneObject = {Name: "The Twinning", Rate: 0}
export const ZONE_AMAUROT: ZoneObject = {Name: "Amaurot", Rate: 105}
export const ZONE_MT_GULG: ZoneObject = {Name: "Mt. Gulg", Rate: 102}
export const ZONE_AKADAEMIA_ANYDER: ZoneObject = {Name: "Akadaemia Anyder", Rate: 0}
export const ZONE_MALIKAHS_WELL: ZoneObject = {Name: "Malikah's Well", Rate: 102}
export const ZONE_HOLMINSTER_SWITCH: ZoneObject = {Name: "Holminster Switch", Rate: 102}
export const ZONE_THE_SYRCUS_TRENCH: ZoneObject = {Name: "The Syrcus Trench", Rate: 0}
export const ZONE_THE_PENDANTS_PERSONAL_SUITE: ZoneObject = {Name: "The Pendants Personal Suite", Rate: 112}
export const ZONE_THE_OCULAR: ZoneObject = {Name: "The Ocular", Rate: 0}
export const ZONE_DUTIFUL_SISTERS_OF_THE_EDELWEISS: ZoneObject = {Name: "Dutiful Sisters of the Edelweiss", Rate: 15}
export const ZONE_DOCK_STOREHOUSE: ZoneObject = {Name: "Dock Storehouse", Rate: 18}
export const ZONE_THE_NABAATH_MINES: ZoneObject = {Name: "The Nabaath Mines", Rate: 108}
export const ZONE_RONKAN_REFLECTIONS: ZoneObject = {Name: "Ronkan Reflections", Rate: 110}
export const ZONE_THE_CROWN_OF_THE_IMMACULATE: ZoneObject = {Name: "The Crown of the Immaculate", Rate: 102}
export const ZONE_THE_CONFESSIONAL_OF_TOUPASA_THE_ELDER: ZoneObject = {Name: "The Confessional of Toupasa the Elder", Rate: 102}
export const ZONE_THE_DANCING_PLAGUE: ZoneObject = {Name: "The Dancing Plague", Rate: 103}
export const ZONE_THE_DYING_GASP: ZoneObject = {Name: "The Dying Gasp", Rate: 105}
export const ZONE_THE_CORE: ZoneObject = {Name: "The Core", Rate: 0}
export const ZONE_THE_HALO: ZoneObject = {Name: "The Halo", Rate: 0}
export const ZONE_THE_NEREUS_TRENCH: ZoneObject = {Name: "The Nereus Trench", Rate: 38}
export const ZONE_ATLAS_PEAK: ZoneObject = {Name: "Atlas Peak", Rate: 23}
export const ZONE_THE_DUNGEONS_OF_LYHE_GHIAH: ZoneObject = {Name: "The Dungeons of Lyhe Ghiah", Rate: 0}
export const ZONE_THE_EMPTY: ZoneObject = {Name: "The Empty", Rate: 0}
export const ZONE_THE_GRAND_COSMOS: ZoneObject = {Name: "The Grand Cosmos", Rate: 0}
export const ZONE_ONSAL_HAKAIR: ZoneObject = {Name: "Onsal Hakair", Rate: 117}
export const ZONE_THE_COPIED_FACTORY: ZoneObject = {Name: "The Copied Factory", Rate: 0}
export const ZONE_LIMINAL_SPACE: ZoneObject = {Name: "Liminal Space", Rate: 0}
export const ZONE_THE_FIRMAMENT: ZoneObject = {Name: "The Firmament", Rate: 47}
export const ZONE_EXCAVATION_TUNNELS: ZoneObject = {Name: "Excavation Tunnels", Rate: 0}
export const ZONE_LYHE_MHEG: ZoneObject = {Name: "Lyhe Mheg", Rate: 40}
export const ZONE_THE_IMPERIAL_PALACE: ZoneObject = {Name: "The Imperial Palace", Rate: 0}
export const ZONE_CINDER_DRIFT: ZoneObject = {Name: "Cinder Drift", Rate: 28}
export const ZONE_ANAMNESIS_ANYDER: ZoneObject = {Name: "Anamnesis Anyder", Rate: 0}
export const ZONE_THE_GANDOF_THUNDER_PLAINS: ZoneObject = {Name: "The Gandof Thunder Plains", Rate: 0}
export const ZONE_ASHFALL: ZoneObject = {Name: "Ashfall", Rate: 0}
export const ZONE_THE_HEROES_GAUNTLET: ZoneObject = {Name: "The Heroes' Gauntlet", Rate: 125}
export const ZONE_TRIALS_THRESHOLD: ZoneObject = {Name: "Trial's Threshold", Rate: 0}
export const ZONE_GREAT_GLACIER: ZoneObject = {Name: "Great Glacier", Rate: 46}
export const ZONE_CIDS_MEMORY: ZoneObject = {Name: "Cid's Memory", Rate: 123}
export const ZONE_THE_FALLING_CITY_OF_NYM: ZoneObject = {Name: "The Falling City of Nym", Rate: 0}
export const ZONE_FROZEN_REFLECTIONS: ZoneObject = {Name: "Frozen Reflections", Rate: 46}
export const ZONE_GANGOS: ZoneObject = {Name: "Gangos", Rate: 0}
export const ZONE_THE_ENDEAVOR: ZoneObject = {Name: "The Endeavor", Rate: 14}
export const ZONE_BOZJAN_SOUTHERN_FRONT: ZoneObject = {Name: "Bozjan Southern Front", Rate: 124}
export const ZONE_TRANSMISSION_CONTROL: ZoneObject = {Name: "Transmission Control", Rate: 123}
export const ZONE_THE_PUPPETS_BUNKER: ZoneObject = {Name: "The Puppets' Bunker", Rate: 0}
export const ZONE_THE_SEAT_OF_SACRIFICE: ZoneObject = {Name: "The Seat of Sacrifice", Rate: 125}
export const ZONE_THE_RIFT: ZoneObject = {Name: "The Rift", Rate: 125}
export const ZONE_ANOGGS_LAIR: ZoneObject = {Name: "Anogg's Lair", Rate: 0}
export const ZONE_CASTRUM_LACUS_LITORE: ZoneObject = {Name: "Castrum Lacus Litore", Rate: 124}
export const ZONE_TERNCLIFF: ZoneObject = {Name: "Terncliff", Rate: 0}
export const ZONE_TERNCLIFF_BAY: ZoneObject = {Name: "Terncliff Bay", Rate: 0}
export const ZONE_MATOYAS_RELICT: ZoneObject = {Name: "Matoya's Relict", Rate: 0}
export const ZONE_SPHERE_OF_NAUGHT: ZoneObject = {Name: "Sphere of Naught", Rate: 0}
export const ZONE_THE_GARDEN_OF_NOWHERE: ZoneObject = {Name: "The Garden of Nowhere", Rate: 0}
export const ZONE_LAXAN_LOFT: ZoneObject = {Name: "Laxan Loft", Rate: 0}
export const ZONE_CASTRUM_MARINUM_DRYDOCKS: ZoneObject = {Name: "Castrum Marinum Drydocks", Rate: 0}
export const ZONE_THE_SHIFTING_OUBLIETTES_OF_LYHE_GHIAH: ZoneObject = {Name: "The Shifting Oubliettes of Lyhe Ghiah", Rate: 0}
export const ZONE_DELUBRUM_REGINAE: ZoneObject = {Name: "Delubrum Reginae", Rate: 0}
export const ZONE_THE_LAST_TRACE: ZoneObject = {Name: "The Last Trace", Rate: 0}
export const ZONE_BYGONE_GAOL: ZoneObject = {Name: "Bygone Gaol", Rate: 0}
export const ZONE_THE_TOWER_AT_PARADIGMS_BREACH: ZoneObject = {Name: "The Tower at Paradigm's Breach", Rate: 0}
export const ZONE_ZADNOR: ZoneObject = {Name: "Zadnor", Rate: 130}
export const ZONE_PAGLTHAN: ZoneObject = {Name: "Paglth'an", Rate: 0}
export const ZONE_GSAVIOR_DECK: ZoneObject = {Name: "G-Savior Deck", Rate: 0}
export const ZONE_THE_DALRIADA: ZoneObject = {Name: "The Dalriada", Rate: 130}
export const ZONE_THE_DARK_INSIDE: ZoneObject = {Name: "The Dark Inside", Rate: 139}
export const ZONE_THE_MOTHERCRYSTAL: ZoneObject = {Name: "The Mothercrystal", Rate: 139}
export const ZONE_THE_FINAL_DAY: ZoneObject = {Name: "The Final Day", Rate: 116}
export const ZONE_EMPYREUM: ZoneObject = {Name: "Empyreum", Rate: 142}
export const ZONE_INGLESIDE_APARTMENT_LOBBY: ZoneObject = {Name: "Ingleside Apartment Lobby", Rate: 0}
export const ZONE_PRIVATE_COTTAGE__EMPYREUM: ZoneObject = {Name: "Private Cottage - Empyreum", Rate: 0}
export const ZONE_PRIVATE_HOUSE__EMPYREUM: ZoneObject = {Name: "Private House - Empyreum", Rate: 0}
export const ZONE_PRIVATE_MANSION__EMPYREUM: ZoneObject = {Name: "Private Mansion - Empyreum", Rate: 0}
export const ZONE_COMPANY_WORKSHOP__EMPYREUM: ZoneObject = {Name: "Company Workshop - Empyreum", Rate: 0}
export const ZONE_PRIVATE_CHAMBERS__EMPYREUM: ZoneObject = {Name: "Private Chambers - Empyreum", Rate: 0}
export const ZONE_INGLESIDE_APARTMENT: ZoneObject = {Name: "Ingleside Apartment", Rate: 0}
export const ZONE_OLD_SHARLAYAN: ZoneObject = {Name: "Old Sharlayan", Rate: 137}
export const ZONE_RADZATHAN: ZoneObject = {Name: "Radz-at-Han", Rate: 138}
export const ZONE_LABYRINTHOS: ZoneObject = {Name: "Labyrinthos", Rate: 131}
export const ZONE_THAVNAIR: ZoneObject = {Name: "Thavnair", Rate: 132}
export const ZONE_GARLEMALD: ZoneObject = {Name: "Garlemald", Rate: 133}
export const ZONE_MARE_LAMENTORUM: ZoneObject = {Name: "Mare Lamentorum", Rate: 135}
export const ZONE_ULTIMA_THULE: ZoneObject = {Name: "Ultima Thule", Rate: 136}
export const ZONE_ELPIS: ZoneObject = {Name: "Elpis", Rate: 134}
export const ZONE_THE_TOWER_OF_ZOT: ZoneObject = {Name: "The Tower of Zot", Rate: 0}
export const ZONE_THE_PHANTOMS_FEAST: ZoneObject = {Name: "The Phantoms' Feast", Rate: 0}
export const ZONE_SMILETON: ZoneObject = {Name: "Smileton", Rate: 0}
export const ZONE_THE_GATES_OF_PANDÆMONIUM: ZoneObject = {Name: "The Gates of Pandæmonium", Rate: 145}
export const ZONE_KTISIS_HYPERBOREIA: ZoneObject = {Name: "Ktisis Hyperboreia", Rate: 0}
export const ZONE_THE_STIGMA_DREAMSCAPE: ZoneObject = {Name: "The Stigma Dreamscape", Rate: 140}
export const ZONE_THE_AITIASCOPE: ZoneObject = {Name: "The Aitiascope", Rate: 0}
export const ZONE_THE_FERVID_LIMBO: ZoneObject = {Name: "The Fervid Limbo", Rate: 145}
export const ZONE_THE_TOWER_OF_BABIL: ZoneObject = {Name: "The Tower of Babil", Rate: 28}
export const ZONE_THE_EXCITATRON_6000: ZoneObject = {Name: "The Excitatron 6000", Rate: 0}
export const ZONE_THE_STAGNANT_LIMBO: ZoneObject = {Name: "The Stagnant Limbo", Rate: 145}
export const ZONE_THE_SANGUINE_LIMBO: ZoneObject = {Name: "The Sanguine Limbo", Rate: 145}
export const ZONE_THE_DEAD_ENDS: ZoneObject = {Name: "The Dead Ends", Rate: 144}
export const ZONE_VANASPATI: ZoneObject = {Name: "Vanaspati", Rate: 141}
export const ZONE_LEMURES_HEADQUARTERS: ZoneObject = {Name: "Lemures Headquarters", Rate: 0}
export const ZONE_MAIN_HALL: ZoneObject = {Name: "Main Hall", Rate: 137}
export const ZONE_ANDRON: ZoneObject = {Name: "Andron", Rate: 137}
export const ZONE_STRATEGY_ROOM: ZoneObject = {Name: "Strategy Room", Rate: 0}
export const ZONE_MAGNA_GLACIES: ZoneObject = {Name: "Magna Glacies", Rate: 0}
export const ZONE_BEYOND_THE_STARS: ZoneObject = {Name: "Beyond the Stars", Rate: 143}
export const ZONE_THE_NETHERGATE: ZoneObject = {Name: "The Nethergate", Rate: 0}
export const ZONE_PROPYLAION: ZoneObject = {Name: "Propylaion", Rate: 0}
export const ZONE_ALZADAALS_LEGACY: ZoneObject = {Name: "Alzadaal's Legacy", Rate: 0}
export const ZONE_AGLAIA: ZoneObject = {Name: "Aglaia", Rate: 147}
export const ZONE_MEDIAS_RES: ZoneObject = {Name: "Medias Res", Rate: 0}
export const ZONE_THE_PALAISTRA: ZoneObject = {Name: "The Palaistra", Rate: 0}
export const ZONE_THE_VOLCANIC_HEART: ZoneObject = {Name: "The Volcanic Heart", Rate: 0}
export const ZONE_THE_PORTA_DECUMANA: ZoneObject = {Name: "The Porta Decumana", Rate: 0}
export const ZONE_THE_OMPHALOS: ZoneObject = {Name: "The Omphalos", Rate: 147}
export const ZONE_RESTRICTED_ARCHIVES: ZoneObject = {Name: "Restricted Archives", Rate: 137}
export const ZONE_THE_FELL_COURT_OF_TROIA: ZoneObject = {Name: "The Fell Court of Troia", Rate: 149}
export const ZONE_THE_PESTILENT_PURGATORY: ZoneObject = {Name: "The Pestilent Purgatory", Rate: 145}
export const ZONE_UNNAMED_ISLAND: ZoneObject = {Name: "Unnamed Island", Rate: 148}
export const ZONE_ZEROS_DOMAIN: ZoneObject = {Name: "Zero's Domain", Rate: 149}
export const ZONE_MEGHADUTA_GUEST_CHAMBERS: ZoneObject = {Name: "Meghaduta Guest Chambers", Rate: 138}
export const ZONE_SNEAKY_HOLLOW: ZoneObject = {Name: "Sneaky Hollow", Rate: 0}
export const ZONE_STORMS_CROWN: ZoneObject = {Name: "Storm's Crown", Rate: 149}
export const ZONE_THE_HOLLOW_PURGATORY: ZoneObject = {Name: "The Hollow Purgatory", Rate: 145}
export const ZONE_ELYSION: ZoneObject = {Name: "Elysion", Rate: 136}
export const ZONE_THE_SILDIHN_SUBTERRANE: ZoneObject = {Name: "The Sil'dihn Subterrane", Rate: 0}
export const ZONE_ANOTHER_SILDIHN_SUBTERRANE: ZoneObject = {Name: "Another Sil'dihn Subterrane", Rate: 0}
export const ZONE_THE_CAUSTIC_PURGATORY: ZoneObject = {Name: "The Caustic Purgatory", Rate: 145}
export const ZONE_STYGIAN_INSENESCENCE_CELLS: ZoneObject = {Name: "Stygian Insenescence Cells", Rate: 145}
export const ZONE_EUPHROSYNE: ZoneObject = {Name: "Euphrosyne", Rate: 147}
export const ZONE_LAPIS_MANALIS: ZoneObject = {Name: "Lapis Manalis", Rate: 42}
export const ZONE_THE_SHIFTING_GYMNASION_AGONON: ZoneObject = {Name: "The Shifting Gymnasion Agonon", Rate: 0}
export const ZONE_SYLPHSTEP: ZoneObject = {Name: "Sylphstep", Rate: 0}
export const ZONE_EUREKA_ORTHOS: ZoneObject = {Name: "Eureka Orthos", Rate: 0}
export const ZONE_THE_CLOCKWORK_CASTLETOWN: ZoneObject = {Name: "The Clockwork Castletown", Rate: 0}
export const ZONE_MOUNT_ORDEALS: ZoneObject = {Name: "Mount Ordeals", Rate: 0}
export const ZONE_KHADGA: ZoneObject = {Name: "Khadga", Rate: 0}
export const ZONE_THE_VOIDCAST_DAIS: ZoneObject = {Name: "The Voidcast Dais", Rate: 149}
export const ZONE_THE_AETHERFONT: ZoneObject = {Name: "The Aetherfont", Rate: 0}
export const ZONE_THE_DÆMONS_NEST: ZoneObject = {Name: "The Dæmons' Nest", Rate: 145}
export const ZONE_ASCENSION: ZoneObject = {Name: "Ascension", Rate: 145}
export const ZONE_APEX_OF_CREATION: ZoneObject = {Name: "Apex of Creation", Rate: 145}
export const ZONE_THE_AETHERIAL_SLOUGH: ZoneObject = {Name: "The Aetherial Slough", Rate: 0}
export const ZONE_THE_GILDED_ARAYA: ZoneObject = {Name: "The Gilded Araya", Rate: 114}
export const ZONE_THE_CHAMBER_OF_FOURTEEN: ZoneObject = {Name: "The Chamber of Fourteen", Rate: 145}
export const ZONE_ESTINIENS_CHAMBERS: ZoneObject = {Name: "Estinien's Chambers", Rate: 138}
export const ZONE_SENATUS: ZoneObject = {Name: "Senatus", Rate: 133}
export const ZONE_THE_RED_MOON: ZoneObject = {Name: "The Red Moon", Rate: 149}
export const ZONE_MOUNT_ROKKON: ZoneObject = {Name: "Mount Rokkon", Rate: 0}
export const ZONE_ANOTHER_MOUNT_ROKKON: ZoneObject = {Name: "Another Mount Rokkon", Rate: 74}
export const ZONE_THE_RED_SANDS: ZoneObject = {Name: "The Red Sands", Rate: 0}
export const ZONE_TULIYOLLAL: ZoneObject = {Name: "Tuliyollal", Rate: 159}
export const ZONE_SOLUTION_NINE: ZoneObject = {Name: "Solution Nine", Rate: 163}
export const ZONE_URQOPACHA: ZoneObject = {Name: "Urqopacha", Rate: 160}
export const ZONE_KOZAMAUKA: ZoneObject = {Name: "Kozama'uka", Rate: 161}
export const ZONE_YAK_TEL: ZoneObject = {Name: "Yak T'el", Rate: 162}
export const ZONE_SHAALOANI: ZoneObject = {Name: "Shaaloani", Rate: 164}
export const ZONE_HERITAGE_FOUND: ZoneObject = {Name: "Heritage Found", Rate: 165}
export const ZONE_LIVING_MEMORY: ZoneObject = {Name: "Living Memory", Rate: 166}
export const ZONE_THE_LUNAR_SUBTERRANE: ZoneObject = {Name: "The Lunar Subterrane", Rate: 149}
export const ZONE_ALOALO_ISLAND: ZoneObject = {Name: "Aloalo Island", Rate: 0}
export const ZONE_ANOTHER_ALOALO_ISLAND: ZoneObject = {Name: "Another Aloalo Island", Rate: 0}
export const ZONE_BLUNDERVILLE: ZoneObject = {Name: "Blunderville", Rate: 0}
export const ZONE_THALEIA: ZoneObject = {Name: "Thaleia", Rate: 147}
export const ZONE_BLUNDERVILLE_SQUARE: ZoneObject = {Name: "Blunderville Square", Rate: 0}
export const ZONE_THE_ABYSSAL_FRACTURE: ZoneObject = {Name: "The Abyssal Fracture", Rate: 149}
export const ZONE_CENOTE_JA_JA_GURAL: ZoneObject = {Name: "Cenote Ja Ja Gural", Rate: 0}
export const ZONE_IHUYKATUMU: ZoneObject = {Name: "Ihuykatumu", Rate: 0}
export const ZONE_VANGUARD: ZoneObject = {Name: "Vanguard", Rate: 0}
export const ZONE_TENDER_VALLEY: ZoneObject = {Name: "Tender Valley", Rate: 0}
export const ZONE_WORQOR_ZORMOR: ZoneObject = {Name: "Worqor Zormor", Rate: 0}
export const ZONE_ORIGENICS: ZoneObject = {Name: "Origenics", Rate: 156}
export const ZONE_ALEXANDRIA: ZoneObject = {Name: "Alexandria", Rate: 157}
export const ZONE_THE_SKYDEEP_CENOTE: ZoneObject = {Name: "The Skydeep Cenote", Rate: 0}
export const ZONE_STRAYBOROUGH: ZoneObject = {Name: "Strayborough", Rate: 150}
export const ZONE_LOVELY_LOVERING: ZoneObject = {Name: "Lovely Lovering", Rate: 0}
export const ZONE_THE_THUNDERING: ZoneObject = {Name: "The Thundering", Rate: 0}
export const ZONE_WORQOR_LAR_DOR: ZoneObject = {Name: "Worqor Lar Dor", Rate: 0}
export const ZONE_BLASTING_RING: ZoneObject = {Name: "Blasting Ring", Rate: 0}
export const ZONE_SCRATCHING_RING: ZoneObject = {Name: "Scratching Ring", Rate: 0}
export const ZONE_INTERPHOS: ZoneObject = {Name: "Interphos", Rate: 157}
export const ZONE_SUMMIT_OF_EVERKEEP: ZoneObject = {Name: "Summit of Everkeep", Rate: 158}
export const ZONE_SUNPERCH: ZoneObject = {Name: "Sunperch", Rate: 159}
export const ZONE_EARTHEN_SKY_HIDEOUT: ZoneObject = {Name: "Earthen Sky Hideout", Rate: 165}
export const ZONE_MAIN_DECK: ZoneObject = {Name: "Main Deck", Rate: 0}
export const ZONE_THE_BACKROOM: ZoneObject = {Name: "The Backroom", Rate: 0}
export const ZONE_SKYDEEP_CENOTE_INNER_CHAMBER: ZoneObject = {Name: "Skydeep Cenote Inner Chamber", Rate: 0}
export const ZONE_TRITAILS_TRAINING: ZoneObject = {Name: "Tritails Training", Rate: 0}
export const ZONE_GREENROOM: ZoneObject = {Name: "Greenroom", Rate: 0}
export const ZONE_THE_FORARD_CABINS: ZoneObject = {Name: "The For'ard Cabins", Rate: 159}
export const ZONE_MANOR_BASEMENT: ZoneObject = {Name: "Manor Basement", Rate: 0}
export const ZONE_DREAMLIKE_PALACE: ZoneObject = {Name: "Dreamlike Palace", Rate: 0}
export const ZONE_YUWEYAWATA: ZoneObject = {Name: "Yuweyawata", Rate: 86}
export const ZONE_JEUNO_THE_FIRST_WALK: ZoneObject = {Name: "Jeuno: The First Walk", Rate: 150}
export const ZONE_LOWER_JEUNO: ZoneObject = {Name: "Lower Jeuno", Rate: 0}
export const ZONE_STARLIGHT_STALLS: ZoneObject = {Name: "Starlight Stalls", Rate: 27}
export const ZONE_HALL_OF_THE_UNBOUND: ZoneObject = {Name: "Hall of the Unbound", Rate: 0}
export const ZONE_NORVRANDT: ZoneObject = {Name: "Norvrandt", Rate: 0}
export const ZONE_HYDAELYN: ZoneObject = {Name: "Hydaelyn", Rate: 0}
export const ZONE_ZORGOR_THE_BOUNDLESS: ZoneObject = {Name: "Zorgor the Boundless", Rate: 0}
export const ZONE_SOUTH_HORN: ZoneObject = {Name: "South Horn", Rate: 168}
export const ZONE_TOWER_OF_BLOOD: ZoneObject = {Name: "Tower of Blood", Rate: 168}
export const ZONE_REBEL_RING: ZoneObject = {Name: "Rebel Ring", Rate: 0}
export const ZONE_GROOVY_RING: ZoneObject = {Name: "Groovy Ring", Rate: 0}
export const ZONE_HUNTERS_RING: ZoneObject = {Name: "Hunter's Ring", Rate: 0}
export const ZONE_HUNTING_GROUND: ZoneObject = {Name: "Hunting Ground", Rate: 0}
export const ZONE_THE_UNDERKEEP: ZoneObject = {Name: "The Underkeep", Rate: 0}
export const ZONE_DEMOLITION_SITE: ZoneObject = {Name: "Demolition Site", Rate: 0}
export const ZONE_SINUS_ARDORUM: ZoneObject = {Name: "Sinus Ardorum", Rate: 169}
export const ZONE_BREAK_ROOM: ZoneObject = {Name: "Break Room", Rate: 0}
export const ZONE_THRONE_ROOM: ZoneObject = {Name: "Throne Room", Rate: 0}
export const ZONE_PHANTOM_VILLAGE: ZoneObject = {Name: "Phantom Village", Rate: 0}
export const ZONE_RECOLLECTION: ZoneObject = {Name: "Recollection", Rate: 0}
export const ZONE_SAN_DORIA_THE_SECOND_WALK: ZoneObject = {Name: "San d'Oria: The Second Walk", Rate: 150}
export const ZONE_THE_AGELESS_NECROPOLIS: ZoneObject = {Name: "The Ageless Necropolis", Rate: 0}
export const ZONE_THE_LIGHTLESS_ABYSS: ZoneObject = {Name: "The Lightless Abyss", Rate: 0}
export const ZONE_THE_MESO_TERMINAL: ZoneObject = {Name: "The Meso Terminal", Rate: 0}
export const ZONE_VAULT_ONEIRON: ZoneObject = {Name: "Vault Oneiron", Rate: 0}
export const ZONE_THE_BAYSIDE_BATTLEGROUND: ZoneObject = {Name: "The Bayside Battleground", Rate: 0}
export const ZONE_CONTAINMENT_COMPLEX_1029: ZoneObject = {Name: "Containment Complex 10-29", Rate: 0}
export const ZONE_PHAENNA: ZoneObject = {Name: "Phaenna", Rate: 171}
